import Foundation
import Testing

@testable import MLXLLM

extension UnitTests {
    /// Configurations of `MLXLLM` decoded from a JSON that sets each key,
    /// also the optional keys, to a value that is not the default. The
    /// expected lines were written by hand from the JSON and the `CodingKeys`
    /// of each type.
    enum LLMFullKeyCases {
        static let all: [ConfigurationDecodingCase] = [
            .init(
                "Bitnet: BitnetConfiguration", MLXLLM.BitnetConfiguration.self,
                json:
                    #"{"attention_bias":true,"head_dim":1206,"hidden_size":1201,"intermediate_size":1203,"max_position_embeddings":1207,"mlp_bias":false,"model_type":"bitnet_custom","num_attention_heads":1204,"num_hidden_layers":1202,"num_key_value_heads":1208,"rms_norm_eps":0.5,"rope_scaling":{"factor":4},"rope_theta":3.5,"rope_traditional":true,"tie_word_embeddings":false,"vocab_size":1205}"#,
                requiredKeys: [],
                fields: [
                    "attentionBias=true",
                    "attentionHeads=1204",
                    "headDimensions=1206",
                    "hiddenLayers=1202",
                    "hiddenSize=1201",
                    "intermediateSize=1203",
                    "kvHeads=1208",
                    "maxPositionEmbeddings=1207",
                    "mlpBias=false",
                    "modelType=bitnet_custom",
                    "rmsNormEps=0.5",
                    "ropeScaling[factor]=int(4)",
                    "ropeTheta=3.5",
                    "ropeTraditional=true",
                    "tieWordEmbeddings=false",
                    "vocabularySize=1205",
                ]),
            .init(
                "DeepseekV4: DeepseekV4Configuration", MLXLLM.DeepseekV4Configuration.self,
                json:
                    #"{"compress_ratios":[0,1812],"compress_rope_theta":1.5,"hc_eps":0.25,"hc_mult":1818,"hc_sinkhorn_iters":1819,"head_dim":1806,"hidden_size":1802,"index_head_dim":1822,"index_n_heads":1821,"index_topk":1823,"max_position_embeddings":1820,"moe_intermediate_size":1803,"n_routed_experts":1813,"n_shared_experts":1814,"norm_topk_prob":false,"num_attention_heads":1805,"num_experts_per_tok":1815,"num_hash_layers":1816,"num_hidden_layers":1804,"num_nextn_predict_layers":1817,"o_groups":1809,"o_lora_rank":1810,"q_lora_rank":1807,"qk_rope_head_dim":1808,"rms_norm_eps":0.5,"rope_scaling":{"factor":16,"type":"yarn"},"rope_theta":4.5,"routed_scaling_factor":2.5,"scoring_func":"sigmoid_custom","sliding_window":1811,"swiglu_limit":3.5,"vocab_size":1801}"#,
                requiredKeys: [],
                fields: [
                    "compressRatios[0]=0",
                    "compressRatios[1]=1812",
                    "compressRopeTheta=1.5",
                    "hcEps=0.25",
                    "hcMult=1818",
                    "hcSinkhornIters=1819",
                    "headDim=1806",
                    "hiddenSize=1802",
                    "indexHeadDim=1822",
                    "indexNHeads=1821",
                    "indexTopk=1823",
                    "maxPositionEmbeddings=1820",
                    "moeIntermediateSize=1803",
                    "nRoutedExperts=1813",
                    "nSharedExperts=1814",
                    "normTopkProb=false",
                    "numAttentionHeads=1805",
                    "numExpertsPerTok=1815",
                    "numHashLayers=1816",
                    "numHiddenLayers=1804",
                    "numNextnPredictLayers=1817",
                    "oGroups=1809",
                    "oLoraRank=1810",
                    "qLoraRank=1807",
                    "qkRopeHeadDim=1808",
                    "rmsNormEps=0.5",
                    "ropeScaling[factor]=int(16)",
                    #"ropeScaling[type]=string("yarn")"#,
                    "ropeTheta=4.5",
                    "routedScalingFactor=2.5",
                    "scoringFunc=sigmoid_custom",
                    "slidingWindow=1811",
                    "swiguLimit=3.5",
                    "vocabSize=1801",
                ]),
            .init(
                "FalconH1: FalconH1Configuration", MLXLLM.FalconH1Configuration.self,
                json:
                    #"{"attention_bias":true,"attention_dropout":0.5,"attention_in_multiplier":1.5,"attention_out_multiplier":2.5,"bos_token_id":901,"embedding_multiplier":3.5,"eos_token_id":902,"head_dim":903,"hidden_act":"gelu_custom","hidden_size":904,"initializer_range":0.25,"intermediate_size":905,"key_multiplier":4.5,"lm_head_multiplier":5.5,"mamba_chunk_size":906,"mamba_conv_bias":false,"mamba_d_conv":907,"mamba_d_head":908,"mamba_d_ssm":909,"mamba_d_state":910,"mamba_expand":911,"mamba_n_groups":912,"mamba_n_heads":913,"mamba_norm_before_gate":false,"mamba_proj_bias":true,"mamba_rms_norm":true,"mamba_use_mlp":false,"max_position_embeddings":914,"mlp_bias":true,"mlp_expansion_factor":915,"mlp_multipliers":[6.5,7.5],"model_type":"falcon_custom","num_attention_heads":916,"num_hidden_layers":917,"num_key_value_heads":918,"num_logits_to_keep":919,"pad_token_id":920,"projectors_bias":true,"rms_norm_eps":0.125,"rope_scaling":8.5,"rope_theta":9.5,"rope_traditional":true,"ssm_in_multiplier":10.5,"ssm_multipliers":[11.5],"ssm_out_multiplier":12.5,"tie_word_embeddings":true,"torch_dtype":"float16","vocab_size":921}"#,
                requiredKeys: [],
                fields: [
                    "attentionBias=true",
                    "attentionDropout=0.5",
                    "attentionInMultiplier=1.5",
                    "attentionOutMultiplier=2.5",
                    "bosTokenId=901",
                    "embeddingMultiplier=3.5",
                    "eosTokenId=902",
                    "headDim=903",
                    "hiddenAct=gelu_custom",
                    "hiddenSize=904",
                    "initializerRange=0.25",
                    "intermediateSize=905",
                    "keyMultiplier=4.5",
                    "lmHeadMultiplier=5.5",
                    "mambaChunkSize=906",
                    "mambaConvBias=false",
                    "mambaDConv=907",
                    "mambaDHead=908",
                    "mambaDSSM=909",
                    "mambaDState=910",
                    "mambaExpand=911",
                    "mambaNGroups=912",
                    "mambaNHeads=913",
                    "mambaNormBeforeGate=false",
                    "mambaProjBias=true",
                    "mambaRMSNorm=true",
                    "mambaUseMLP=false",
                    "maxPositionEmbeddings=914",
                    "mlpBias=true",
                    "mlpExpansionFactor=915",
                    "mlpMultipliers[0]=6.5",
                    "mlpMultipliers[1]=7.5",
                    "modelType=falcon_custom",
                    "numAttentionHeads=916",
                    "numHiddenLayers=917",
                    "numKeyValueHeads=918",
                    "numLogitsToKeep=919",
                    "padTokenId=920",
                    "projectorsBias=true",
                    "rmsNormEps=0.125",
                    "ropeScaling=8.5",
                    "ropeTheta=9.5",
                    "ropeTraditional=true",
                    "ssmInMultiplier=10.5",
                    "ssmMultipliers[0]=11.5",
                    "ssmOutMultiplier=12.5",
                    "tieWordEmbeddings=true",
                    "torchDtype=float16",
                    "vocabSize=921",
                ]),
            .init(
                "Gemma3Text: Gemma3TextConfiguration", MLXLLM.Gemma3TextConfiguration.self,
                json:
                    #"{"head_dim":1305,"hidden_size":1301,"intermediate_size":1303,"max_position_embeddings":1310,"model_type":"gemma3_custom_text","num_attention_heads":1304,"num_hidden_layers":1302,"num_key_value_heads":1307,"query_pre_attn_scalar":3.5,"rms_norm_eps":0.5,"rope_local_base_freq":2.5,"rope_scaling":{"factor":8,"rope_type":"linear"},"rope_theta":1.5,"rope_traditional":true,"sliding_window":1308,"sliding_window_pattern":1309,"vocab_size":1306}"#,
                requiredKeys: [],
                fields: [
                    "attentionHeads=1304",
                    "headDim=1305",
                    "hiddenLayers=1302",
                    "hiddenSize=1301",
                    "intermediateSize=1303",
                    "kvHeads=1307",
                    "maxPositionEmbeddings=1310",
                    "modelType=gemma3_custom_text",
                    "queryPreAttnScalar=3.5",
                    "rmsNormEps=0.5",
                    "ropeLocalBaseFreq=2.5",
                    "ropeScaling[factor]=int(8)",
                    #"ropeScaling[rope_type]=string("linear")"#,
                    "ropeTheta=1.5",
                    "ropeTraditional=true",
                    "slidingWindow=1308",
                    "slidingWindowPattern=1309",
                    "vocabularySize=1306",
                ]),
            .init(
                "Gemma4: Gemma4Configuration", MLXLLM.Gemma4Configuration.self,
                json:
                    #"{"model_type":"gemma4_custom","quantization":{"bits":5,"group_size":16,"lm_head":false,"mode":"nvfp4"},"text_config":{"attention_k_eq_v":true,"enable_moe_block":true,"final_logit_softcapping":12.5,"global_head_dim":405,"global_partial_rotary_factor":0.625,"head_dim":404,"hidden_size":401,"hidden_size_per_layer_input":411,"intermediate_size":402,"layer_types":["full_attention","sliding_attention","full_attention","sliding_attention"],"max_position_embeddings":414,"model_type":"gemma4_custom_text","moe_intermediate_size":417,"num_attention_heads":403,"num_experts":415,"num_global_key_value_heads":409,"num_hidden_layers":3,"num_key_value_heads":408,"num_kv_shared_layers":410,"rms_norm_eps":0.125,"rope_parameters":{"full_attention":{"partial_rotary_factor":0.375,"rope_theta":2.5},"sliding_attention":{"rope_theta":1.5}},"sliding_window":412,"sliding_window_pattern":413,"tie_word_embeddings":false,"top_k_experts":416,"use_bidirectional_attention":"vision","use_double_wide_mlp":false,"vocab_size":406,"vocab_size_per_layer_input":407},"vocab_size":420}"#,
                requiredKeys: [],
                fields: [
                    "modelType=gemma4_custom",
                    "textConfig.attentionKeqV=true",
                    "textConfig.enableMoeBlock=true",
                    "textConfig.finalLogitSoftcapping=12.5",
                    "textConfig.fullPartialRotaryFactor=0.375",
                    "textConfig.fullRopeTheta=2.5",
                    "textConfig.globalHeadDim=405",
                    "textConfig.globalPartialRotaryFactor=0.625",
                    "textConfig.headDim=404",
                    "textConfig.hiddenSize=401",
                    "textConfig.hiddenSizePerLayerInput=411",
                    "textConfig.intermediateSize=402",
                    "textConfig.layerTypes[0]=full_attention",
                    "textConfig.layerTypes[1]=sliding_attention",
                    "textConfig.layerTypes[2]=full_attention",
                    "textConfig.maxPositionEmbeddings=414",
                    "textConfig.modelType=gemma4_custom_text",
                    "textConfig.moeIntermediateSize=417",
                    "textConfig.numAttentionHeads=403",
                    "textConfig.numExperts=415",
                    "textConfig.numGlobalKeyValueHeads=409",
                    "textConfig.numHiddenLayers=3",
                    "textConfig.numKeyValueHeads=408",
                    "textConfig.numKvSharedLayers=410",
                    "textConfig.perLayerQuantization.perLayerQuantization[lm_head]=skip",
                    "textConfig.perLayerQuantization.quantization._mode=nvfp4",
                    "textConfig.perLayerQuantization.quantization.bits=5",
                    "textConfig.perLayerQuantization.quantization.groupSize=16",
                    "textConfig.quantizationBits=5",
                    "textConfig.quantizationGroupSize=16",
                    "textConfig.quantizationMode=nvfp4",
                    "textConfig.rmsNormEps=0.125",
                    "textConfig.ropeParameters[full_attention][partial_rotary_factor]=float(0.375)",
                    "textConfig.ropeParameters[full_attention][rope_theta]=float(2.5)",
                    "textConfig.ropeParameters[sliding_attention][rope_theta]=float(1.5)",
                    "textConfig.slidingRopeTheta=1.5",
                    "textConfig.slidingWindow=412",
                    "textConfig.slidingWindowPattern=413",
                    "textConfig.tieWordEmbeddings=false",
                    "textConfig.topKExperts=416",
                    "textConfig.useBidirectionalAttention=vision",
                    "textConfig.useDoubleWideMlp=false",
                    "textConfig.vocabSize=420",
                    "textConfig.vocabSizePerLayerInput=407",
                    "vocabSize=420",
                ]),
            .init(
                "Gemma4MTPConfigurationValidation: Gemma4AssistantTextConfigurationPreflight",
                MLXLLM.Gemma4AssistantTextConfigurationPreflight.self,
                json: #"{"num_hidden_layers":430,"sliding_window_pattern":431}"#,
                requiredKeys: [],
                fields: [
                    "numHiddenLayers=430",
                    "slidingWindowPattern=431",
                ]),
            .init(
                "Gemma4Text: Gemma4TextConfiguration", MLXLLM.Gemma4TextConfiguration.self,
                json:
                    #"{"attention_k_eq_v":true,"enable_moe_block":true,"final_logit_softcapping":12.5,"global_head_dim":405,"global_partial_rotary_factor":0.625,"head_dim":404,"hidden_size":401,"hidden_size_per_layer_input":411,"intermediate_size":402,"layer_types":["full_attention","sliding_attention","full_attention","sliding_attention"],"max_position_embeddings":414,"model_type":"gemma4_custom_text","moe_intermediate_size":417,"num_attention_heads":403,"num_experts":415,"num_global_key_value_heads":409,"num_hidden_layers":3,"num_key_value_heads":408,"num_kv_shared_layers":410,"quantization":{"bits":3,"group_size":32,"language_model.layers.0.mlp":false,"mode":"mxfp4"},"rms_norm_eps":0.125,"rope_parameters":{"full_attention":{"partial_rotary_factor":0.375,"rope_theta":2.5},"sliding_attention":{"rope_theta":1.5}},"sliding_window":412,"sliding_window_pattern":413,"tie_word_embeddings":false,"top_k_experts":416,"use_bidirectional_attention":"vision","use_double_wide_mlp":false,"vocab_size":406,"vocab_size_per_layer_input":407}"#,
                requiredKeys: [],
                fields: [
                    "attentionKeqV=true",
                    "enableMoeBlock=true",
                    "finalLogitSoftcapping=12.5",
                    "fullPartialRotaryFactor=0.375",
                    "fullRopeTheta=2.5",
                    "globalHeadDim=405",
                    "globalPartialRotaryFactor=0.625",
                    "headDim=404",
                    "hiddenSize=401",
                    "hiddenSizePerLayerInput=411",
                    "intermediateSize=402",
                    "layerTypes[0]=full_attention",
                    "layerTypes[1]=sliding_attention",
                    "layerTypes[2]=full_attention",
                    "maxPositionEmbeddings=414",
                    "modelType=gemma4_custom_text",
                    "moeIntermediateSize=417",
                    "numAttentionHeads=403",
                    "numExperts=415",
                    "numGlobalKeyValueHeads=409",
                    "numHiddenLayers=3",
                    "numKeyValueHeads=408",
                    "numKvSharedLayers=410",
                    "perLayerQuantization.perLayerQuantization[language_model.layers.0.mlp]=skip",
                    "perLayerQuantization.quantization._mode=mxfp4",
                    "perLayerQuantization.quantization.bits=3",
                    "perLayerQuantization.quantization.groupSize=32",
                    "quantizationBits=3",
                    "quantizationGroupSize=32",
                    "quantizationMode=mxfp4",
                    "rmsNormEps=0.125",
                    "ropeParameters[full_attention][partial_rotary_factor]=float(0.375)",
                    "ropeParameters[full_attention][rope_theta]=float(2.5)",
                    "ropeParameters[sliding_attention][rope_theta]=float(1.5)",
                    "slidingRopeTheta=1.5",
                    "slidingWindow=412",
                    "slidingWindowPattern=413",
                    "tieWordEmbeddings=false",
                    "topKExperts=416",
                    "useBidirectionalAttention=vision",
                    "useDoubleWideMlp=false",
                    "vocabSize=406",
                    "vocabSizePerLayerInput=407",
                ]),
            .init(
                "Gemma4Text: Gemma4WeightQuantizationMetadata",
                MLXLLM.Gemma4WeightQuantizationMetadata.self,
                json: #"{"bits":7,"group_size":48,"mode":"mxfp8"}"#,
                requiredKeys: [],
                fields: [
                    "bits=7",
                    "groupSize=48",
                    "mode=mxfp8",
                ]),
            .init(
                "Laguna: LagunaConfiguration", MLXLLM.LagunaConfiguration.self,
                json:
                    #"{"attention_bias":true,"decoder_sparse_step":617,"gating":"per_element","head_dim":607,"hidden_size":602,"intermediate_size":603,"layer_types":["sliding_attention","full_attention"],"max_position_embeddings":608,"mlp_layer_types":["dense","sparse"],"mlp_only_layers":[612],"moe_intermediate_size":615,"moe_routed_scaling_factor":6.5,"moe_router_logit_softcapping":7.5,"norm_topk_prob":false,"num_attention_heads":605,"num_attention_heads_per_layer":[610,611],"num_experts":613,"num_experts_per_tok":614,"num_hidden_layers":604,"num_key_value_heads":606,"qkv_bias":false,"quantization":{"bits":619,"group_size":618,"mode":"mxfp4"},"rms_norm_eps":0.5,"rope_parameters":{"full_attention":{"rope_theta":5.5}},"rope_theta":4.5,"shared_expert_intermediate_size":616,"sliding_window":609,"tie_word_embeddings":true,"vocab_size":601}"#,
                requiredKeys: [],
                fields: [
                    "attentionBias=true",
                    "decoderSparseStep=617",
                    "gating=perElement",
                    "headDim=607",
                    "hiddenSize=602",
                    "intermediateSize=603",
                    "layerTypes[0]=sliding_attention",
                    "layerTypes[1]=full_attention",
                    "maxPositionEmbeddings=608",
                    "mlpLayerTypes[0]=dense",
                    "mlpLayerTypes[1]=sparse",
                    "mlpOnlyLayers[0]=612",
                    "moeIntermediateSize=615",
                    "moeRoutedScalingFactor=6.5",
                    "moeRouterLogitSoftcapping=7.5",
                    "normTopkProb=false",
                    "numAttentionHeads=605",
                    "numAttentionHeadsPerLayer[0]=610",
                    "numAttentionHeadsPerLayer[1]=611",
                    "numExperts=613",
                    "numExpertsPerTok=614",
                    "numHiddenLayers=604",
                    "numKeyValueHeads=606",
                    "qkvBias=false",
                    "quantBits=619",
                    "quantGroupSize=618",
                    "quantMode=mxfp4",
                    "rmsNormEps=0.5",
                    "ropeParametersByType[full_attention][rope_theta]=float(5.5)",
                    "ropeTheta=4.5",
                    "sharedExpertIntermediateSize=616",
                    "slidingWindow=609",
                    "tieWordEmbeddings=true",
                    "vocabSize=601",
                ]),
            .init(
                "NemotronH35: NemotronH35Configuration", MLXLLM.NemotronH35Configuration.self,
                json:
                    #"{"attention_bias":false,"chunk_size":1719,"conv_kernel":1708,"head_dim":1716,"hidden_size":1702,"intermediate_size":1710,"layers_block_type":["mamba","attention","mlp","moe"],"mamba_head_dim":1706,"mamba_num_heads":1705,"mamba_proj_bias":true,"mamba_ssm_cache_dtype":"float32","mlp_bias":false,"model_type":"nemotron_35_custom","moe_intermediate_size":1711,"moe_shared_expert_intermediate_size":1712,"mtp_layers_block_type":["mamba"],"n_group":1717,"n_groups":1709,"n_routed_experts":1713,"n_shared_experts":1714,"norm_eps":0.125,"norm_topk_prob":true,"num_attention_heads":1703,"num_experts_per_tok":1715,"num_hidden_layers":4,"num_key_value_heads":1704,"num_nextn_predict_layers":1720,"rope_theta":5.5,"routed_scaling_factor":6.5,"ssm_state_size":1707,"tie_word_embeddings":false,"time_step_limit":[0.5,7.5],"topk_group":1718,"use_bias":true,"use_conv_bias":true,"vocab_size":1701}"#,
                requiredKeys: [],
                fields: [
                    "hasExplicitExecutionLimits=true",
                    "target.attentionBias=false",
                    "target.chunkSize=1719",
                    "target.convKernel=1708",
                    "target.headDim=1716",
                    "target.hiddenSize=1702",
                    "target.hybridOverridePattern=M*-E",
                    "target.intermediateSize=1710",
                    "target.layerNormEpsilon=0.125",
                    "target.mambaHeadDim=1706",
                    "target.mambaNumHeads=1705",
                    "target.mambaProjBias=true",
                    "target.mambaSSMCacheDType=float32",
                    "target.mlpBias=false",
                    "target.modelType=nemotron_35_custom",
                    "target.moeIntermediateSize=1711",
                    "target.moeSharedExpertIntermediateSize=1712",
                    "target.mtpLayersBlockType[0]=mamba",
                    "target.nGroup=1717",
                    "target.nGroups=1709",
                    "target.nRoutedExperts=1713",
                    "target.nSharedExperts=1714",
                    "target.normTopkProb=true",
                    "target.numAttentionHeads=1703",
                    "target.numExpertsPerTok=1715",
                    "target.numHiddenLayers=4",
                    "target.numKeyValueHeads=1704",
                    "target.numNextnPredictLayers=1720",
                    "target.ropeTheta=5.5",
                    "target.routedScalingFactor=6.5",
                    "target.ssmStateSize=1707",
                    "target.tieWordEmbeddings=false",
                    "target.timeStepLimitMax=7.5",
                    "target.timeStepLimitMin=0.5",
                    "target.topkGroup=1718",
                    "target.useBias=true",
                    "target.useConvBias=true",
                    "target.vocabSize=1701",
                ]),
            .init(
                "NemotronH: NemotronHConfiguration", MLXLLM.NemotronHConfiguration.self,
                json:
                    #"{"attention_bias":true,"chunk_size":1620,"conv_kernel":1609,"head_dim":1617,"hidden_size":1602,"hybrid_override_pattern":"M*E-","intermediate_size":1611,"layer_norm_epsilon":0.5,"mamba_head_dim":1607,"mamba_num_heads":1606,"mamba_proj_bias":false,"mamba_ssm_cache_dtype":"bfloat16","mlp_bias":true,"model_type":"nemotron_custom","moe_intermediate_size":1612,"moe_shared_expert_intermediate_size":1613,"mtp_layers_block_type":["attention","moe"],"n_group":1618,"n_groups":1610,"n_routed_experts":1614,"n_shared_experts":1615,"norm_topk_prob":false,"num_attention_heads":1604,"num_experts_per_tok":1616,"num_hidden_layers":1603,"num_key_value_heads":1605,"num_nextn_predict_layers":1621,"rope_theta":1.5,"routed_scaling_factor":2.5,"ssm_state_size":1608,"tie_word_embeddings":true,"time_step_limit_max":3.5,"time_step_limit_min":0.25,"topk_group":1619,"use_bias":false,"use_conv_bias":false,"vocab_size":1601}"#,
                requiredKeys: [],
                fields: [
                    "attentionBias=true",
                    "chunkSize=1620",
                    "convKernel=1609",
                    "headDim=1617",
                    "hiddenSize=1602",
                    "hybridOverridePattern=M*E-",
                    "intermediateSize=1611",
                    "layerNormEpsilon=0.5",
                    "mambaHeadDim=1607",
                    "mambaNumHeads=1606",
                    "mambaProjBias=false",
                    "mambaSSMCacheDType=bfloat16",
                    "mlpBias=true",
                    "modelType=nemotron_custom",
                    "moeIntermediateSize=1612",
                    "moeSharedExpertIntermediateSize=1613",
                    "mtpLayersBlockType[0]=attention",
                    "mtpLayersBlockType[1]=moe",
                    "nGroup=1618",
                    "nGroups=1610",
                    "nRoutedExperts=1614",
                    "nSharedExperts=1615",
                    "normTopkProb=false",
                    "numAttentionHeads=1604",
                    "numExpertsPerTok=1616",
                    "numHiddenLayers=1603",
                    "numKeyValueHeads=1605",
                    "numNextnPredictLayers=1621",
                    "ropeTheta=1.5",
                    "routedScalingFactor=2.5",
                    "ssmStateSize=1608",
                    "tieWordEmbeddings=true",
                    "timeStepLimitMax=3.5",
                    "timeStepLimitMin=0.25",
                    "topkGroup=1619",
                    "useBias=false",
                    "useConvBias=false",
                    "vocabSize=1601",
                ]),
            .init(
                "Phi3: RopeScalingWithFactorArrays", MLXLLM.RopeScalingWithFactorArrays.self,
                json:
                    #"{"factor":1.25,"long_factor":[1.5,2.5],"long_mscale":3.25,"short_factor":[0.5],"short_mscale":0.75,"type":"longrope"}"#,
                requiredKeys: [],
                fields: [
                    "factor=1.25",
                    "longFactor[0]=1.5",
                    "longFactor[1]=2.5",
                    "longMScale=3.25",
                    "shortFactor[0]=0.5",
                    "shortMScale=0.75",
                    "type=longrope",
                ]),
            .init(
                "Qwen35: Qwen35TextConfiguration", MLXLLM.Qwen35TextConfiguration.self,
                json:
                    #"{"attention_bias":false,"decoder_sparse_step":717,"full_attention_interval":714,"head_dim":713,"hidden_size":701,"intermediate_size":703,"linear_conv_kernel_dim":710,"linear_key_head_dim":708,"linear_num_key_heads":707,"linear_num_value_heads":706,"linear_value_head_dim":709,"max_position_embeddings":712,"model_type":"qwen35_custom_text","moe_intermediate_size":719,"mtp_num_hidden_layers":720,"norm_topk_prob":true,"num_attention_heads":704,"num_experts":715,"num_experts_per_tok":716,"num_hidden_layers":702,"num_key_value_heads":705,"partial_rotary_factor":0.625,"rms_norm_eps":0.5,"rope_scaling":{"factor":2.5,"mrope_section":[2,3,4],"type":"linear"},"rope_theta":8.5,"shared_expert_intermediate_size":718,"tie_word_embeddings":true,"vocab_size":711}"#,
                requiredKeys: [],
                fields: [
                    "attentionBias=false",
                    "attentionHeads=704",
                    "decoderSparseStep=717",
                    "fullAttentionInterval=714",
                    "headDim=713",
                    "hiddenLayers=702",
                    "hiddenSize=701",
                    "intermediateSize=703",
                    "kvHeads=705",
                    "linearConvKernelDim=710",
                    "linearKeyHeadDim=708",
                    "linearNumKeyHeads=707",
                    "linearNumValueHeads=706",
                    "linearValueHeadDim=709",
                    "maxPositionEmbeddings=712",
                    "modelType=qwen35_custom_text",
                    "moeIntermediateSize=719",
                    "mropeSection[0]=2",
                    "mropeSection[1]=3",
                    "mropeSection[2]=4",
                    "mtpNumHiddenLayers=720",
                    "normTopkProb=true",
                    "numExperts=715",
                    "numExpertsPerTok=716",
                    "partialRotaryFactor=0.625",
                    "rmsNormEps=0.5",
                    "ropeScaling[factor]=float(2.5)",
                    "ropeScaling[mrope_section]=ints([2, 3, 4])",
                    #"ropeScaling[type]=string("linear")"#,
                    "ropeTheta=8.5",
                    "sharedExpertIntermediateSize=718",
                    "tieWordEmbeddings=true",
                    "vocabularySize=711",
                ]),
            .init(
                "Qwen35MoE: Qwen35Configuration", MLXLLM.Qwen35Configuration.self,
                json:
                    #"{"model_type":"qwen35_custom","text_config":{"attention_bias":false,"decoder_sparse_step":717,"full_attention_interval":714,"head_dim":713,"hidden_size":701,"intermediate_size":703,"linear_conv_kernel_dim":710,"linear_key_head_dim":708,"linear_num_key_heads":707,"linear_num_value_heads":706,"linear_value_head_dim":709,"max_position_embeddings":712,"model_type":"qwen35_custom_text","moe_intermediate_size":719,"mtp_num_hidden_layers":720,"norm_topk_prob":true,"num_attention_heads":704,"num_experts":715,"num_experts_per_tok":716,"num_hidden_layers":702,"num_key_value_heads":705,"partial_rotary_factor":0.625,"rms_norm_eps":0.5,"rope_scaling":{"factor":2.5,"mrope_section":[2,3,4],"type":"linear"},"rope_theta":8.5,"shared_expert_intermediate_size":718,"tie_word_embeddings":true,"vocab_size":711}}"#,
                requiredKeys: [],
                fields: [
                    "modelType=qwen35_custom",
                    "textConfig.attentionBias=false",
                    "textConfig.attentionHeads=704",
                    "textConfig.decoderSparseStep=717",
                    "textConfig.fullAttentionInterval=714",
                    "textConfig.headDim=713",
                    "textConfig.hiddenLayers=702",
                    "textConfig.hiddenSize=701",
                    "textConfig.intermediateSize=703",
                    "textConfig.kvHeads=705",
                    "textConfig.linearConvKernelDim=710",
                    "textConfig.linearKeyHeadDim=708",
                    "textConfig.linearNumKeyHeads=707",
                    "textConfig.linearNumValueHeads=706",
                    "textConfig.linearValueHeadDim=709",
                    "textConfig.maxPositionEmbeddings=712",
                    "textConfig.modelType=qwen35_custom_text",
                    "textConfig.moeIntermediateSize=719",
                    "textConfig.mropeSection[0]=2",
                    "textConfig.mropeSection[1]=3",
                    "textConfig.mropeSection[2]=4",
                    "textConfig.mtpNumHiddenLayers=720",
                    "textConfig.normTopkProb=true",
                    "textConfig.numExperts=715",
                    "textConfig.numExpertsPerTok=716",
                    "textConfig.partialRotaryFactor=0.625",
                    "textConfig.rmsNormEps=0.5",
                    "textConfig.ropeScaling[factor]=float(2.5)",
                    "textConfig.ropeScaling[mrope_section]=ints([2, 3, 4])",
                    #"textConfig.ropeScaling[type]=string("linear")"#,
                    "textConfig.ropeTheta=8.5",
                    "textConfig.sharedExpertIntermediateSize=718",
                    "textConfig.tieWordEmbeddings=true",
                    "textConfig.vocabularySize=711",
                ]),
            .init(
                "Qwen3: Qwen3Configuration", MLXLLM.Qwen3Configuration.self,
                json:
                    #"{"head_dim":1007,"hidden_size":1001,"intermediate_size":1003,"max_position_embeddings":1008,"num_attention_heads":1004,"num_hidden_layers":1002,"num_key_value_heads":1006,"rms_norm_eps":0.5,"rope_scaling":{"factor":2.5,"type":"yarn"},"rope_theta":1.5,"tie_word_embeddings":true,"vocab_size":1005}"#,
                requiredKeys: [],
                fields: [
                    "attentionHeads=1004",
                    "headDim=1007",
                    "hiddenLayers=1002",
                    "hiddenSize=1001",
                    "intermediateSize=1003",
                    "kvHeads=1006",
                    "maxPositionEmbeddings=1008",
                    "rmsNormEps=0.5",
                    "ropeScaling[factor]=float(2.5)",
                    #"ropeScaling[type]=string("yarn")"#,
                    "ropeTheta=1.5",
                    "tieWordEmbeddings=true",
                    "vocabularySize=1005",
                ]),
            .init(
                "Qwen3Next: Qwen3NextConfiguration", MLXLLM.Qwen3NextConfiguration.self,
                json:
                    #"{"attention_bias":true,"decoder_sparse_step":1112,"full_attention_interval":1121,"head_dim":1120,"hidden_size":1101,"intermediate_size":1103,"linear_conv_kernel_dim":1109,"linear_key_head_dim":1107,"linear_num_key_heads":1106,"linear_num_value_heads":1105,"linear_value_head_dim":1108,"max_position_embeddings":1119,"mlp_only_layers":[1114,1115],"model_type":"qwen3_next_custom","moe_intermediate_size":1116,"norm_topk_prob":true,"num_attention_heads":1104,"num_experts":1110,"num_experts_per_tok":1111,"num_hidden_layers":1102,"num_key_value_heads":1118,"partial_rotary_factor":0.375,"rms_norm_eps":0.25,"rope_scaling":{"type":"linear"},"rope_theta":2.5,"shared_expert_intermediate_size":1113,"tie_word_embeddings":false,"vocab_size":1117}"#,
                requiredKeys: [],
                fields: [
                    "attentionBias=true",
                    "attentionHeads=1104",
                    "decoderSparseStep=1112",
                    "fullAttentionInterval=1121",
                    "headDim=1120",
                    "hiddenLayers=1102",
                    "hiddenSize=1101",
                    "intermediateSize=1103",
                    "kvHeads=1118",
                    "linearConvKernelDim=1109",
                    "linearKeyHeadDim=1107",
                    "linearNumKeyHeads=1106",
                    "linearNumValueHeads=1105",
                    "linearValueHeadDim=1108",
                    "maxPositionEmbeddings=1119",
                    "mlpOnlyLayers[0]=1114",
                    "mlpOnlyLayers[1]=1115",
                    "modelType=qwen3_next_custom",
                    "moeIntermediateSize=1116",
                    "normTopkProb=true",
                    "numExperts=1110",
                    "numExpertsPerTok=1111",
                    "partialRotaryFactor=0.375",
                    "rmsNormEps=0.25",
                    #"ropeScaling[type]=string("linear")"#,
                    "ropeTheta=2.5",
                    "sharedExpertIntermediateSize=1113",
                    "tieWordEmbeddings=false",
                    "vocabularySize=1117",
                ]),
            .init(
                "Qwen4Exp: Qwen4ExpConfiguration", MLXLLM.Qwen4ExpConfiguration.self,
                json:
                    #"{"image_token_id":140,"model_type":"qwen4_custom","text_config":{"attention_bias":true,"eos_token_id":[132,133],"full_attention_interval":113,"hc_count":114,"hc_lowrank":115,"head_dim":105,"heads_per_ngram":119,"hidden_size":101,"indexer_budget":126,"indexer_compress_ratio":127,"indexer_head_dim":125,"indexer_kv_heads":124,"indexer_n_heads":123,"layer_types":["full_attention","linear_attention"],"linear_conv_kernel_dim":110,"linear_key_head_dim":108,"linear_num_key_heads":107,"linear_num_value_heads":106,"linear_value_head_dim":109,"make_ngram_vocab_size_divisible_by":121,"max_position_embeddings":112,"model_type":"qwen4_custom_text","moe_intermediate_size":131,"mtp_num_hidden_layers":134,"ngram_size":118,"ngram_vocab_size_base":120,"norm_topk_prob":false,"num_attention_heads":103,"num_experts":128,"num_experts_per_tok":129,"num_hidden_layers":2,"num_key_value_heads":104,"output_gate_type":"silu","ple_conv_kernel_size":117,"ple_embed_dim":116,"ple_layer_ids":[1,2],"rms_norm_eps":0.5,"rope_parameters":{"mrope_section":[3,4,5],"partial_rotary_factor":0.75,"rope_theta":2.5},"seed":135,"shared_expert_intermediate_size":130,"split_ngram_parts":122,"tie_word_embeddings":true,"vocab_size":111},"video_token_id":141}"#,
                requiredKeys: [],
                fields: [
                    "imageTokenId=140",
                    "modelType=qwen4_custom",
                    "textConfig.attentionBias=true",
                    "textConfig.attentionHeads=103",
                    "textConfig.eosTokenId[0]=132",
                    "textConfig.eosTokenId[1]=133",
                    "textConfig.fullAttentionInterval=113",
                    "textConfig.hcCount=114",
                    "textConfig.hcLowrank=115",
                    "textConfig.headDim=105",
                    "textConfig.headsPerNgram=119",
                    "textConfig.hiddenLayers=2",
                    "textConfig.hiddenSize=101",
                    "textConfig.indexerBudget=126",
                    "textConfig.indexerCompressRatio=127",
                    "textConfig.indexerHeadDim=125",
                    "textConfig.indexerKVHeads=124",
                    "textConfig.indexerNHeads=123",
                    "textConfig.kvHeads=104",
                    "textConfig.layerTypes[0]=qwen_sparse_attention",
                    "textConfig.layerTypes[1]=linear_attention",
                    "textConfig.linearConvKernelDim=110",
                    "textConfig.linearKeyHeadDim=108",
                    "textConfig.linearNumKeyHeads=107",
                    "textConfig.linearNumValueHeads=106",
                    "textConfig.linearValueHeadDim=109",
                    "textConfig.makeNgramVocabSizeDivisibleBy=121",
                    "textConfig.maxPositionEmbeddings=112",
                    "textConfig.modelType=qwen4_custom_text",
                    "textConfig.moeIntermediateSize=131",
                    "textConfig.mropeSection[0]=3",
                    "textConfig.mropeSection[1]=4",
                    "textConfig.mropeSection[2]=5",
                    "textConfig.mtpNumHiddenLayers=134",
                    "textConfig.ngramSize=118",
                    "textConfig.ngramVocabSizeBase=120",
                    "textConfig.normTopkProb=false",
                    "textConfig.numExperts=128",
                    "textConfig.numExpertsPerTok=129",
                    "textConfig.outputGateType=silu",
                    "textConfig.partialRotaryFactor=0.75",
                    "textConfig.pleConvKernelSize=117",
                    "textConfig.pleEmbedDim=116",
                    "textConfig.pleLayerIds[0]=1",
                    "textConfig.pleLayerIds[1]=2",
                    "textConfig.rmsNormEps=0.5",
                    "textConfig.ropeTheta=2.5",
                    "textConfig.seed=135",
                    "textConfig.sharedExpertIntermediateSize=130",
                    "textConfig.splitNgramParts=122",
                    "textConfig.tieWordEmbeddings=true",
                    "textConfig.vocabularySize=111",
                    "videoTokenId=141",
                ]),
            .init(
                "Qwen4Exp: Qwen4ExpTextConfiguration", MLXLLM.Qwen4ExpTextConfiguration.self,
                json:
                    #"{"attention_bias":true,"eos_token_id":[132,133],"full_attention_interval":113,"hc_count":114,"hc_lowrank":115,"head_dim":105,"heads_per_ngram":119,"hidden_size":101,"indexer_budget":126,"indexer_compress_ratio":127,"indexer_head_dim":125,"indexer_kv_heads":124,"indexer_n_heads":123,"layer_types":["full_attention","linear_attention"],"linear_conv_kernel_dim":110,"linear_key_head_dim":108,"linear_num_key_heads":107,"linear_num_value_heads":106,"linear_value_head_dim":109,"make_ngram_vocab_size_divisible_by":121,"max_position_embeddings":112,"model_type":"qwen4_custom_text","moe_intermediate_size":131,"mtp_num_hidden_layers":134,"ngram_size":118,"ngram_vocab_size_base":120,"norm_topk_prob":false,"num_attention_heads":103,"num_experts":128,"num_experts_per_tok":129,"num_hidden_layers":2,"num_key_value_heads":104,"output_gate_type":"silu","ple_conv_kernel_size":117,"ple_embed_dim":116,"ple_layer_ids":[1,2],"rms_norm_eps":0.5,"rope_parameters":{"mrope_section":[3,4,5],"partial_rotary_factor":0.75,"rope_theta":2.5},"seed":135,"shared_expert_intermediate_size":130,"split_ngram_parts":122,"tie_word_embeddings":true,"vocab_size":111}"#,
                requiredKeys: [],
                fields: [
                    "attentionBias=true",
                    "attentionHeads=103",
                    "eosTokenId[0]=132",
                    "eosTokenId[1]=133",
                    "fullAttentionInterval=113",
                    "hcCount=114",
                    "hcLowrank=115",
                    "headDim=105",
                    "headsPerNgram=119",
                    "hiddenLayers=2",
                    "hiddenSize=101",
                    "indexerBudget=126",
                    "indexerCompressRatio=127",
                    "indexerHeadDim=125",
                    "indexerKVHeads=124",
                    "indexerNHeads=123",
                    "kvHeads=104",
                    "layerTypes[0]=qwen_sparse_attention",
                    "layerTypes[1]=linear_attention",
                    "linearConvKernelDim=110",
                    "linearKeyHeadDim=108",
                    "linearNumKeyHeads=107",
                    "linearNumValueHeads=106",
                    "linearValueHeadDim=109",
                    "makeNgramVocabSizeDivisibleBy=121",
                    "maxPositionEmbeddings=112",
                    "modelType=qwen4_custom_text",
                    "moeIntermediateSize=131",
                    "mropeSection[0]=3",
                    "mropeSection[1]=4",
                    "mropeSection[2]=5",
                    "mtpNumHiddenLayers=134",
                    "ngramSize=118",
                    "ngramVocabSizeBase=120",
                    "normTopkProb=false",
                    "numExperts=128",
                    "numExpertsPerTok=129",
                    "outputGateType=silu",
                    "partialRotaryFactor=0.75",
                    "pleConvKernelSize=117",
                    "pleEmbedDim=116",
                    "pleLayerIds[0]=1",
                    "pleLayerIds[1]=2",
                    "rmsNormEps=0.5",
                    "ropeTheta=2.5",
                    "seed=135",
                    "sharedExpertIntermediateSize=130",
                    "splitNgramParts=122",
                    "tieWordEmbeddings=true",
                    "vocabularySize=111",
                ]),
        ]
    }
}
