import Foundation
import Testing

@testable import MLXVLM

extension UnitTests {
    /// Decodes each model configuration type of `MLXVLM` from a minimal
    /// `config.json`. Only the configuration is decoded; no model is built.
    @Suite
    struct VLMConfigurationDecodingTests {

        static let cases: [ConfigurationDecodingCase] = [
            .init(
                "FastVLM: FastVLMConfiguration", MLXVLM.FastVLMConfiguration.self,
                json:
                    #"{"eos_token_id":36,"hidden_size":30,"intermediate_size":32,"mm_hidden_size":38,"mm_projector_type":"text","model_type":"text","num_attention_heads":33,"num_hidden_layers":31,"num_key_value_heads":35,"tokenizer_model_max_length":39,"tokenizer_padding_side":"text","vision_config":{"cls_ratio":12,"down_patch_size":13,"down_stride":14,"downsamples":[],"embed_dims":[],"hidden_size":17,"image_size":18,"intermediate_size":19,"layer_scale_init_value":21,"layers":[],"mlp_ratios":[],"num_classes":23,"patch_size":24,"pos_embs_shapes":[],"projection_dim":26,"repmixer_kernel_size":27,"token_mixers":[]},"vocab_size":34}"#,
                requiredKeys: [
                    "vision_config", "vision_config.cls_ratio", "vision_config.down_patch_size",
                    "vision_config.down_stride", "vision_config.downsamples",
                    "vision_config.embed_dims", "vision_config.hidden_size",
                    "vision_config.image_size", "vision_config.intermediate_size",
                    "vision_config.layers", "vision_config.layer_scale_init_value",
                    "vision_config.mlp_ratios", "vision_config.num_classes",
                    "vision_config.patch_size", "vision_config.pos_embs_shapes",
                    "vision_config.projection_dim", "vision_config.repmixer_kernel_size",
                    "vision_config.token_mixers", "model_type", "hidden_size", "num_hidden_layers",
                    "intermediate_size", "num_attention_heads", "vocab_size", "num_key_value_heads",
                    "eos_token_id", "mm_projector_type", "mm_hidden_size",
                    "tokenizer_model_max_length", "tokenizer_padding_side",
                ],
                fields: [
                    "baseConfiguration._imageTokenIndex=nil",
                    "baseConfiguration.eosTokenId=36",
                    "baseConfiguration.modelType=text",
                    "baseConfiguration.multimodalProjectorHiddenSize=38",
                    "baseConfiguration.multimodalProjectorType=text",
                    "baseConfiguration.tokenizerModelMaxLangth=39",
                    "baseConfiguration.tokenizerPaddingSide=text",
                    "textConfiguration._maxPositionEmbeddings=nil",
                    "textConfiguration._rmsNormEps=nil",
                    "textConfiguration._ropeTheta=nil",
                    "textConfiguration._ropeTraditional=nil",
                    "textConfiguration._tieWordEmbeddings=nil",
                    "textConfiguration.attentionHeads=33",
                    "textConfiguration.hiddenLayers=31",
                    "textConfiguration.hiddenSize=30",
                    "textConfiguration.intermediateSize=32",
                    "textConfiguration.kvHeads=35",
                    "textConfiguration.modelType=text",
                    "textConfiguration.ropeScaling=nil",
                    "textConfiguration.vocabularySize=34",
                    "visionConfiguration.classHeadRatio=12.0",
                    "visionConfiguration.downPatchSize=13",
                    "visionConfiguration.downSamples=[]",
                    "visionConfiguration.downStride=14",
                    "visionConfiguration.embedDimensions=[]",
                    "visionConfiguration.hiddenSize=17",
                    "visionConfiguration.imageSize=18",
                    "visionConfiguration.intermediateSize=19",
                    "visionConfiguration.layerScaleInitValue=21.0",
                    "visionConfiguration.layers=[]",
                    "visionConfiguration.mlpRatios=[]",
                    "visionConfiguration.numClasses=23",
                    "visionConfiguration.patchSize=24",
                    "visionConfiguration.posEmbedShapes=[]",
                    "visionConfiguration.projectionDim=26",
                    "visionConfiguration.repMixerKernelSize=27",
                    "visionConfiguration.tokenMixers=[]",
                ]),
            .init(
                "FastVLM: FastVLMProcessorConfiguration", MLXVLM.FastVLMProcessorConfiguration.self,
                json: #"{"crop_size":{"height":15,"width":14},"image_mean":[],"image_std":[]}"#,
                requiredKeys: [
                    "image_mean", "image_std", "crop_size", "crop_size.width", "crop_size.height",
                ],
                fields: [
                    "cropSize.height=15",
                    "cropSize.width=14",
                    "imageMean=[]",
                    "imageStd=[]",
                ]),
            .init(
                "Gemma3: Gemma3Configuration", MLXVLM.Gemma3Configuration.self,
                json:
                    #"{"mm_tokens_per_image":26,"model_type":"text","text_config":{"hidden_size":13,"intermediate_size":15,"model_type":"text","num_hidden_layers":14,"sliding_window":16},"vision_config":{"hidden_size":20,"image_size":24,"intermediate_size":21,"model_type":"text","num_attention_heads":22,"num_hidden_layers":19,"patch_size":23}}"#,
                requiredKeys: [
                    "text_config", "text_config.model_type", "text_config.hidden_size",
                    "text_config.num_hidden_layers", "text_config.intermediate_size",
                    "text_config.sliding_window", "vision_config", "vision_config.model_type",
                    "vision_config.num_hidden_layers", "vision_config.hidden_size",
                    "vision_config.intermediate_size", "vision_config.num_attention_heads",
                    "vision_config.patch_size", "vision_config.image_size", "model_type",
                    "mm_tokens_per_image",
                ],
                fields: [
                    "_padTokenId=nil",
                    "_vocabularySize=nil",
                    "mmTokensPerImage=26",
                    "modelType=text",
                    "quantization=nil",
                    "textConfiguration._attentionHeads=nil",
                    "textConfiguration._headDim=nil",
                    "textConfiguration._kvHeads=nil",
                    "textConfiguration._queryPreAttnScalar=nil",
                    "textConfiguration.finalLogitSoftcapping=nil",
                    "textConfiguration.hiddenLayers=14",
                    "textConfiguration.hiddenSize=13",
                    "textConfiguration.intermediateSize=15",
                    "textConfiguration.maxPositionEmbeddings=4096",
                    "textConfiguration.mmTokensPerImage=256",
                    "textConfiguration.modelType=text",
                    "textConfiguration.rmsNormEps=1e-06",
                    "textConfiguration.ropeLocalBaseFreq=10000.0",
                    "textConfiguration.ropeScaling=nil",
                    "textConfiguration.ropeTheta=1000000.0",
                    "textConfiguration.ropeTraditional=false",
                    "textConfiguration.slidingWindow=16",
                    "textConfiguration.slidingWindowPattern=6",
                    "textConfiguration.vocabularySize=262208",
                    "visionConfiguration.attentionHeads=22",
                    "visionConfiguration.hiddenLayers=19",
                    "visionConfiguration.hiddenSize=20",
                    "visionConfiguration.imageSize=24",
                    "visionConfiguration.intermediateSize=21",
                    "visionConfiguration.layerNormEps=1e-06",
                    "visionConfiguration.modelType=text",
                    "visionConfiguration.numChannels=3",
                    "visionConfiguration.patchSize=23",
                ]),
            .init(
                "Gemma3: Gemma3ProcessorConfiguration", MLXVLM.Gemma3ProcessorConfiguration.self,
                json:
                    #"{"do_normalize":false,"do_rescale":false,"do_resize":false,"image_mean":[],"image_processor_type":"text","image_seq_length":18,"image_std":[],"processor_class":"text","resample":19,"rescale_factor":20,"size":{"height":22,"width":23}}"#,
                requiredKeys: [
                    "processor_class", "image_processor_type", "do_normalize", "do_rescale",
                    "do_resize", "image_mean", "image_std", "image_seq_length", "resample",
                    "rescale_factor", "size", "size.height", "size.width",
                ],
                fields: [
                    "doConvertRgb=nil",
                    "doNormalize=false",
                    "doPanAndScan=nil",
                    "doRescale=false",
                    "doResize=false",
                    "imageMean=[]",
                    "imageProcessorType=text",
                    "imageSeqLength=18",
                    "imageStd=[]",
                    "imageTokenId=262144",
                    "panAndScanMaxNumCrops=nil",
                    "panAndScanMinCropSize=nil",
                    "panAndScanMinRatioToActivate=nil",
                    "processorClass=text",
                    "resample=19",
                    "rescaleFactor=20.0",
                    "size.height=22",
                    "size.width=23",
                ]),
            .init(
                "Gemma3: Gemma3TextConfiguration", MLXVLM.Gemma3TextConfiguration.self,
                json:
                    #"{"hidden_size":12,"intermediate_size":14,"model_type":"text","num_hidden_layers":13,"sliding_window":15}"#,
                requiredKeys: [
                    "model_type", "hidden_size", "num_hidden_layers", "intermediate_size",
                    "sliding_window",
                ],
                fields: [
                    "_attentionHeads=nil",
                    "_headDim=nil",
                    "_kvHeads=nil",
                    "_queryPreAttnScalar=nil",
                    "finalLogitSoftcapping=nil",
                    "hiddenLayers=13",
                    "hiddenSize=12",
                    "intermediateSize=14",
                    "maxPositionEmbeddings=4096",
                    "mmTokensPerImage=256",
                    "modelType=text",
                    "rmsNormEps=1e-06",
                    "ropeLocalBaseFreq=10000.0",
                    "ropeScaling=nil",
                    "ropeTheta=1000000.0",
                    "ropeTraditional=false",
                    "slidingWindow=15",
                    "slidingWindowPattern=6",
                    "vocabularySize=262208",
                ]),
            .init(
                "Gemma3: Gemma3VisionConfiguration", MLXVLM.Gemma3VisionConfiguration.self,
                json:
                    #"{"hidden_size":13,"image_size":17,"intermediate_size":14,"model_type":"text","num_attention_heads":15,"num_hidden_layers":12,"patch_size":16}"#,
                requiredKeys: [
                    "model_type", "num_hidden_layers", "hidden_size", "intermediate_size",
                    "num_attention_heads", "patch_size", "image_size",
                ],
                fields: [
                    "attentionHeads=15",
                    "hiddenLayers=12",
                    "hiddenSize=13",
                    "imageSize=17",
                    "intermediateSize=14",
                    "layerNormEps=1e-06",
                    "modelType=text",
                    "numChannels=3",
                    "patchSize=16",
                ]),
            .init(
                "Gemma4: Gemma4Configuration", MLXVLM.Gemma4Configuration.self,
                json: #"{"text_config":{},"vision_config":{}}"#,
                requiredKeys: ["vision_config"],
                fields: [
                    "imageTokenId=258880",
                    "modelType=gemma4",
                    "quantization=nil",
                    "textConfig.attentionKeqV=false",
                    "textConfig.enableMoeBlock=false",
                    "textConfig.finalLogitSoftcapping=0.0",
                    "textConfig.fullPartialRotaryFactor=0.25",
                    "textConfig.fullRopeTheta=1000000.0",
                    "textConfig.globalHeadDim=512",
                    "textConfig.globalPartialRotaryFactor=0.25",
                    "textConfig.headDim=256",
                    "textConfig.hiddenSize=2816",
                    "textConfig.hiddenSizePerLayerInput=0",
                    "textConfig.intermediateSize=2112",
                    "textConfig.layerTypes[0]=sliding_attention",
                    "textConfig.layerTypes[10]=sliding_attention",
                    "textConfig.layerTypes[11]=sliding_attention",
                    "textConfig.layerTypes[12]=sliding_attention",
                    "textConfig.layerTypes[13]=sliding_attention",
                    "textConfig.layerTypes[14]=sliding_attention",
                    "textConfig.layerTypes[15]=sliding_attention",
                    "textConfig.layerTypes[16]=sliding_attention",
                    "textConfig.layerTypes[17]=sliding_attention",
                    "textConfig.layerTypes[18]=sliding_attention",
                    "textConfig.layerTypes[19]=sliding_attention",
                    "textConfig.layerTypes[1]=sliding_attention",
                    "textConfig.layerTypes[20]=sliding_attention",
                    "textConfig.layerTypes[21]=sliding_attention",
                    "textConfig.layerTypes[22]=sliding_attention",
                    "textConfig.layerTypes[23]=sliding_attention",
                    "textConfig.layerTypes[24]=sliding_attention",
                    "textConfig.layerTypes[25]=sliding_attention",
                    "textConfig.layerTypes[26]=sliding_attention",
                    "textConfig.layerTypes[27]=sliding_attention",
                    "textConfig.layerTypes[28]=sliding_attention",
                    "textConfig.layerTypes[29]=sliding_attention",
                    "textConfig.layerTypes[2]=sliding_attention",
                    "textConfig.layerTypes[3]=sliding_attention",
                    "textConfig.layerTypes[4]=sliding_attention",
                    "textConfig.layerTypes[5]=sliding_attention",
                    "textConfig.layerTypes[6]=sliding_attention",
                    "textConfig.layerTypes[7]=sliding_attention",
                    "textConfig.layerTypes[8]=sliding_attention",
                    "textConfig.layerTypes[9]=sliding_attention",
                    "textConfig.maxPositionEmbeddings=131072",
                    "textConfig.modelType=gemma4_text",
                    "textConfig.moeIntermediateSize=nil",
                    "textConfig.numAttentionHeads=16",
                    "textConfig.numExperts=nil",
                    "textConfig.numGlobalKeyValueHeads=nil",
                    "textConfig.numHiddenLayers=30",
                    "textConfig.numKeyValueHeads=8",
                    "textConfig.numKvSharedLayers=0",
                    "textConfig.perLayerQuantization=nil",
                    "textConfig.quantizationBits=nil",
                    "textConfig.quantizationGroupSize=nil",
                    "textConfig.quantizationMode=affine",
                    "textConfig.rmsNormEps=1e-06",
                    "textConfig.ropeParameters=nil",
                    "textConfig.slidingRopeTheta=10000.0",
                    "textConfig.slidingWindow=1024",
                    "textConfig.slidingWindowPattern=5",
                    "textConfig.tieWordEmbeddings=true",
                    "textConfig.topKExperts=nil",
                    "textConfig.useBidirectionalAttention=nil",
                    "textConfig.useDoubleWideMlp=false",
                    "textConfig.vocabSize=262144",
                    "textConfig.vocabSizePerLayerInput=0",
                    "videoTokenId=258884",
                    "visionConfig.defaultOutputLength=280",
                    "visionConfig.headDim=64",
                    "visionConfig.hiddenSize=768",
                    "visionConfig.intermediateSize=3072",
                    "visionConfig.numAttentionHeads=12",
                    "visionConfig.numHiddenLayers=16",
                    "visionConfig.numKeyValueHeads=12",
                    "visionConfig.patchSize=16",
                    "visionConfig.poolingKernelSize=3",
                    "visionConfig.positionEmbeddingSize=10240",
                    "visionConfig.rmsNormEps=1e-06",
                    "visionConfig.ropeTheta=100.0",
                    "visionConfig.standardize=false",
                    "visionConfig.useClippedLinears=false",
                    "visionSoftTokensPerImage=280",
                ]),
            .init(
                "Gemma4: Gemma4ProcessorConfiguration", MLXVLM.Gemma4ProcessorConfiguration.self,
                json: "{}",
                requiredKeys: [],
                fields: [
                    "audioSeqLength=750",
                    "boiTokenId=255999",
                    "eoiTokenId=258882",
                    "imageSeqLength=280",
                    "maxSoftTokens=280",
                    "patchSize=16",
                    "poolingKernelSize=3",
                    "processorClass=Gemma4Processor",
                    "videoMaxSoftTokens=70",
                ]),
            .init(
                "Gemma4: Gemma4VisionConfig", MLXVLM.Gemma4VisionConfig.self,
                json: "{}",
                requiredKeys: [],
                fields: [
                    "defaultOutputLength=280",
                    "headDim=64",
                    "hiddenSize=768",
                    "intermediateSize=3072",
                    "numAttentionHeads=12",
                    "numHiddenLayers=16",
                    "numKeyValueHeads=12",
                    "patchSize=16",
                    "poolingKernelSize=3",
                    "positionEmbeddingSize=10240",
                    "rmsNormEps=1e-06",
                    "ropeTheta=100.0",
                    "standardize=false",
                    "useClippedLinears=false",
                ]),
            .init(
                "GlmOcr: GlmOcrConfiguration", MLXVLM.GlmOcrConfiguration.self,
                json:
                    #"{"model_type":"text","text_config":{"head_dim":17,"hidden_size":12,"intermediate_size":14,"num_attention_heads":15,"num_hidden_layers":13,"num_key_value_heads":16,"rope_parameters":{"mrope_section":[]},"vocab_size":18},"vision_config":{"depth":22,"hidden_size":23,"intermediate_size":24,"num_heads":25,"out_hidden_size":27,"patch_size":26,"spatial_merge_size":28,"temporal_patch_size":29}}"#,
                requiredKeys: [
                    "text_config", "text_config.hidden_size", "text_config.num_hidden_layers",
                    "text_config.intermediate_size", "text_config.num_attention_heads",
                    "text_config.num_key_value_heads", "text_config.head_dim",
                    "text_config.vocab_size", "text_config.rope_parameters",
                    "text_config.rope_parameters.mrope_section", "vision_config",
                    "vision_config.depth", "vision_config.hidden_size",
                    "vision_config.intermediate_size", "vision_config.num_heads",
                    "vision_config.patch_size", "vision_config.out_hidden_size",
                    "vision_config.spatial_merge_size", "vision_config.temporal_patch_size",
                    "model_type",
                ],
                fields: [
                    "baseConfiguration._hiddenSize=nil",
                    "baseConfiguration._imageStartTokenId=nil",
                    "baseConfiguration._imageTokenId=nil",
                    "baseConfiguration._videoTokenId=nil",
                    "baseConfiguration._vocabularySize=nil",
                    "baseConfiguration.modelType=text",
                    "textConfiguration._rmsNormEps=nil",
                    "textConfiguration._tieWordEmbeddings=nil",
                    "textConfiguration.attentionHeads=15",
                    "textConfiguration.headDim=17",
                    "textConfiguration.hiddenLayers=13",
                    "textConfiguration.hiddenSize=12",
                    "textConfiguration.intermediateSize=14",
                    "textConfiguration.kvHeads=16",
                    "textConfiguration.ropeParameters._partialRotaryFactor=nil",
                    "textConfiguration.ropeParameters._ropeTheta=nil",
                    "textConfiguration.ropeParameters.mropeSection=[]",
                    "textConfiguration.vocabularySize=18",
                    "visionConfiguration._inChannels=nil",
                    "visionConfiguration._rmsNormEps=nil",
                    "visionConfiguration.depth=22",
                    "visionConfiguration.hiddenSize=23",
                    "visionConfiguration.intermediateSize=24",
                    "visionConfiguration.numHeads=25",
                    "visionConfiguration.outHiddenSize=27",
                    "visionConfiguration.patchSize=26",
                    "visionConfiguration.spatialMergeSize=28",
                    "visionConfiguration.temporalPatchSize=29",
                ]),
            .init(
                "GlmOcr: GlmOcrProcessorConfiguration", MLXVLM.GlmOcrProcessorConfiguration.self,
                json:
                    #"{"image_mean":[],"image_std":[],"merge_size":13,"patch_size":14,"size":{"longest_edge":18,"shortest_edge":17},"temporal_patch_size":15}"#,
                requiredKeys: [
                    "image_mean", "image_std", "merge_size", "patch_size", "temporal_patch_size",
                    "size", "size.shortest_edge", "size.longest_edge",
                ],
                fields: [
                    "imageMean=[]",
                    "imageStd=[]",
                    "mergeSize=13",
                    "patchSize=14",
                    "size.longestEdge=18",
                    "size.shortestEdge=17",
                    "temporalPatchSize=15",
                ]),
            .init(
                "Idefics3: Idefics3Configuration", MLXVLM.Idefics3Configuration.self,
                json:
                    #"{"model_type":"text","text_config":{"hidden_size":13,"intermediate_size":14,"model_type":"text","num_attention_heads":15,"num_key_value_heads":18,"rms_norm_eps":16,"rope_theta":19,"vocab_size":17},"vision_config":{"hidden_size":22,"image_size":25,"model_type":"text","num_attention_heads":23,"patch_size":24}}"#,
                requiredKeys: [
                    "text_config", "text_config.model_type", "text_config.hidden_size",
                    "text_config.intermediate_size", "text_config.num_attention_heads",
                    "text_config.rms_norm_eps", "text_config.vocab_size",
                    "text_config.num_key_value_heads", "text_config.rope_theta", "vision_config",
                    "vision_config.model_type", "vision_config.hidden_size",
                    "vision_config.num_attention_heads", "vision_config.patch_size",
                    "vision_config.image_size", "model_type",
                ],
                fields: [
                    "ignoreIndex=-100",
                    "imageTokenId=49153",
                    "imageTokenIndex=49153",
                    "modelType=text",
                    "scaleFactor=2",
                    "textConfig._numHiddenLayers=nil",
                    "textConfig._ropeTraditional=nil",
                    "textConfig._tieWordEmbeddings=nil",
                    "textConfig.hiddenSize=13",
                    "textConfig.intermediateSize=14",
                    "textConfig.modelType=text",
                    "textConfig.numAttentionHeads=15",
                    "textConfig.numKeyValueHeads=18",
                    "textConfig.rmsNormEps=16.0",
                    "textConfig.ropeTheta=19.0",
                    "textConfig.vocabSize=17",
                    "visionConfig._intermediateSize=nil",
                    "visionConfig._layerNormEps=nil",
                    "visionConfig._numChannels=nil",
                    "visionConfig._numHiddenLayers=nil",
                    "visionConfig.hiddenSize=22",
                    "visionConfig.imageSize=25",
                    "visionConfig.modelType=text",
                    "visionConfig.numAttentionHeads=23",
                    "visionConfig.patchSize=24",
                    "vocabSize=128259",
                ]),
            .init(
                "Idefics3: Idefics3ProcessorConfiguration",
                MLXVLM.Idefics3ProcessorConfiguration.self,
                json: #"{"image_mean":[],"image_std":[],"size":{"longest_edge":14}}"#,
                requiredKeys: ["image_mean", "image_std", "size", "size.longest_edge"],
                fields: [
                    "imageMean=[]",
                    "imageSequenceLength=nil",
                    "imageStd=[]",
                    "size.longestEdge=14",
                ]),
            .init(
                "LFM2VL: LFM2VLConfiguration", MLXVLM.LFM2VLConfiguration.self,
                json:
                    #"{"model_type":"text","text_config":{"hidden_size":13,"model_type":"text","num_attention_heads":15,"num_hidden_layers":14,"num_key_value_heads":16,"vocab_size":17},"vision_config":{"hidden_size":20,"intermediate_size":21,"model_type":"text","num_attention_heads":23,"num_hidden_layers":22}}"#,
                requiredKeys: [
                    "text_config", "text_config.model_type", "text_config.hidden_size",
                    "text_config.num_hidden_layers", "text_config.num_attention_heads",
                    "text_config.num_key_value_heads", "text_config.vocab_size", "vision_config",
                    "vision_config.model_type", "vision_config.hidden_size",
                    "vision_config.intermediate_size", "vision_config.num_hidden_layers",
                    "vision_config.num_attention_heads", "model_type",
                ],
                fields: [
                    "_doImageSplitting=nil",
                    "_downsampleFactor=nil",
                    "_imageTokenId=nil",
                    "_maxImageTokens=nil",
                    "_maxNumPatches=nil",
                    "_minImageTokens=nil",
                    "_minTiles=nil",
                    "_projectorBias=nil",
                    "_projectorHiddenSize=nil",
                    "_projectorUseLayernorm=nil",
                    "_useThumbnail=nil",
                    "_visionFeatureLayer=nil",
                    "modelType=text",
                    "textConfiguration._blockAutoAdjustFFDim=nil",
                    "textConfiguration._blockDim=nil",
                    "textConfiguration._blockFFDim=nil",
                    "textConfiguration._blockFFNDimMultiplier=nil",
                    "textConfiguration._blockMultipleOf=nil",
                    "textConfiguration._convBias=nil",
                    "textConfiguration._convLCache=nil",
                    "textConfiguration._fullAttnIdxs=nil",
                    "textConfiguration._normEps=nil",
                    "textConfiguration._ropeTheta=nil",
                    "textConfiguration.attentionHeads=15",
                    "textConfiguration.hiddenLayers=14",
                    "textConfiguration.hiddenSize=13",
                    "textConfiguration.kvHeads=16",
                    "textConfiguration.layerTypes=nil",
                    "textConfiguration.modelType=text",
                    "textConfiguration.vocabularySize=17",
                    "visionConfiguration._imageSize=nil",
                    "visionConfiguration._layerNormEps=nil",
                    "visionConfiguration._numChannels=nil",
                    "visionConfiguration._numPatches=nil",
                    "visionConfiguration._patchSize=nil",
                    "visionConfiguration.hiddenSize=20",
                    "visionConfiguration.intermediateSize=21",
                    "visionConfiguration.modelType=text",
                    "visionConfiguration.numAttentionHeads=23",
                    "visionConfiguration.numHiddenLayers=22",
                ]),
            .init(
                "LFM2VL: LFM2VLProcessorConfiguration", MLXVLM.LFM2VLProcessorConfiguration.self,
                json: "{}",
                requiredKeys: [],
                fields: [
                    "_downsampleFactor=nil",
                    "_encoderPatchSize=nil",
                    "_imageMean=nil",
                    "_imageStd=nil",
                    "_maxTiles=nil",
                    "_tileSize=nil",
                ]),
            .init(
                "Mistral3: Mistral3VLMConfiguration", MLXVLM.Mistral3VLMConfiguration.self,
                json:
                    #"{"model_type":"text","text_config":{"hidden_size":13,"intermediate_size":15,"model_type":"text","num_attention_heads":16,"num_hidden_layers":14,"rms_norm_eps":17,"vocab_size":18},"vision_config":{"hidden_size":21,"image_size":26,"intermediate_size":24,"model_type":"text","num_attention_heads":23,"num_hidden_layers":22,"patch_size":25}}"#,
                requiredKeys: [
                    "text_config", "text_config.model_type", "text_config.hidden_size",
                    "text_config.num_hidden_layers", "text_config.intermediate_size",
                    "text_config.num_attention_heads", "text_config.rms_norm_eps",
                    "text_config.vocab_size", "vision_config", "vision_config.model_type",
                    "vision_config.hidden_size", "vision_config.num_hidden_layers",
                    "vision_config.num_attention_heads", "vision_config.intermediate_size",
                    "vision_config.patch_size", "vision_config.image_size", "model_type",
                ],
                fields: [
                    "_eosTokenId=nil",
                    "_ignoreIndex=nil",
                    "_imageTokenId=nil",
                    "_imageTokenIndex=nil",
                    "_multimodalProjectorBias=nil",
                    "_spatialMergeSize=nil",
                    "_visionFeatureLayer=nil",
                    "_visionFeatureSelectStrategy=nil",
                    "_vocabSize=nil",
                    "modelType=text",
                    "textConfig._headDim=nil",
                    "textConfig._layerTypes=nil",
                    "textConfig._maxPositionEmbeddings=nil",
                    "textConfig._numKeyValueHeads=nil",
                    "textConfig._ropeParameters=nil",
                    "textConfig._ropeScaling=nil",
                    "textConfig._ropeTheta=nil",
                    "textConfig._ropeTraditional=nil",
                    "textConfig._slidingWindow=nil",
                    "textConfig._tieWordEmbeddings=nil",
                    "textConfig._useQkNorm=nil",
                    "textConfig.hiddenSize=13",
                    "textConfig.intermediateSize=15",
                    "textConfig.modelType=text",
                    "textConfig.numAttentionHeads=16",
                    "textConfig.numHiddenLayers=14",
                    "textConfig.rmsNormEps=17.0",
                    "textConfig.vocabSize=18",
                    "visionConfig._headDim=nil",
                    "visionConfig._numChannels=nil",
                    "visionConfig._rmsNormEps=nil",
                    "visionConfig._ropeTheta=nil",
                    "visionConfig.hiddenSize=21",
                    "visionConfig.imageSize=26",
                    "visionConfig.intermediateSize=24",
                    "visionConfig.modelType=text",
                    "visionConfig.numAttentionHeads=23",
                    "visionConfig.numHiddenLayers=22",
                    "visionConfig.patchSize=25",
                ]),
            .init(
                "Mistral3: Mistral3VLMProcessorConfiguration",
                MLXVLM.Mistral3VLMProcessorConfiguration.self,
                json:
                    #"{"image_processor":{"image_mean":[],"image_std":[],"patch_size":15,"size":{}},"image_token":"text","patch_size":17}"#,
                requiredKeys: [
                    "image_processor", "image_processor.image_mean", "image_processor.image_std",
                    "image_processor.size", "image_processor.patch_size", "image_token",
                    "patch_size",
                ],
                fields: [
                    "imageBreakToken=nil",
                    "imageEndToken=nil",
                    "imageProcessor.doNormalize=nil",
                    "imageProcessor.doRescale=nil",
                    "imageProcessor.doResize=nil",
                    "imageProcessor.imageMean=[]",
                    "imageProcessor.imageStd=[]",
                    "imageProcessor.patchSize=15",
                    "imageProcessor.rescaleFactor=nil",
                    "imageProcessor.size.height=nil",
                    "imageProcessor.size.longestEdge=nil",
                    "imageProcessor.size.width=nil",
                    "imageToken=text",
                    "patchSize=17",
                    "spatialMergeSize=nil",
                ]),
            .init(
                "Mistral3: Mistral3VLMTextConfiguration", MLXVLM.Mistral3VLMTextConfiguration.self,
                json:
                    #"{"hidden_size":12,"intermediate_size":14,"model_type":"text","num_attention_heads":15,"num_hidden_layers":13,"rms_norm_eps":16,"vocab_size":17}"#,
                requiredKeys: [
                    "model_type", "hidden_size", "num_hidden_layers", "intermediate_size",
                    "num_attention_heads", "rms_norm_eps", "vocab_size",
                ],
                fields: [
                    "_headDim=nil",
                    "_layerTypes=nil",
                    "_maxPositionEmbeddings=nil",
                    "_numKeyValueHeads=nil",
                    "_ropeParameters=nil",
                    "_ropeScaling=nil",
                    "_ropeTheta=nil",
                    "_ropeTraditional=nil",
                    "_slidingWindow=nil",
                    "_tieWordEmbeddings=nil",
                    "_useQkNorm=nil",
                    "hiddenSize=12",
                    "intermediateSize=14",
                    "modelType=text",
                    "numAttentionHeads=15",
                    "numHiddenLayers=13",
                    "rmsNormEps=16.0",
                    "vocabSize=17",
                ]),
            .init(
                "Paligemma: PaliGemmaConfiguration", MLXVLM.PaliGemmaConfiguration.self,
                json:
                    #"{"hidden_size":32,"ignore_index":30,"image_token_index":31,"model_type":"text","pad_token_id":33,"text_config":{"hidden_size":13,"intermediate_size":15,"model_type":"text","num_attention_heads":16,"num_hidden_layers":14,"num_key_value_heads":17,"vocab_size":18},"vision_config":{"hidden_size":21,"image_size":27,"intermediate_size":23,"model_type":"text","num_attention_heads":24,"num_hidden_layers":22,"patch_size":25,"projection_dim":26},"vocab_size":29}"#,
                requiredKeys: [
                    "text_config", "text_config.model_type", "text_config.hidden_size",
                    "text_config.num_hidden_layers", "text_config.intermediate_size",
                    "text_config.num_attention_heads", "text_config.num_key_value_heads",
                    "text_config.vocab_size", "vision_config", "vision_config.model_type",
                    "vision_config.hidden_size", "vision_config.num_hidden_layers",
                    "vision_config.intermediate_size", "vision_config.num_attention_heads",
                    "vision_config.patch_size", "vision_config.projection_dim",
                    "vision_config.image_size", "model_type", "vocab_size", "ignore_index",
                    "image_token_index", "hidden_size", "pad_token_id",
                ],
                fields: [
                    "hiddenSize=32",
                    "ignoreIndex=30",
                    "imageTokenIndex=31",
                    "modelType=text",
                    "padTokenId=33",
                    "textConfiguration._rmsNormEps=nil",
                    "textConfiguration._ropeTheta=nil",
                    "textConfiguration._ropeTraditional=nil",
                    "textConfiguration.attentionHeads=16",
                    "textConfiguration.hiddenLayers=14",
                    "textConfiguration.hiddenSize=13",
                    "textConfiguration.intermediateSize=15",
                    "textConfiguration.kvHeads=17",
                    "textConfiguration.modelType=text",
                    "textConfiguration.vocabularySize=18",
                    "visionConfiguration._channels=nil",
                    "visionConfiguration._layerNormEps=nil",
                    "visionConfiguration.attentionHeads=24",
                    "visionConfiguration.hiddenLayers=22",
                    "visionConfiguration.hiddenSize=21",
                    "visionConfiguration.imageSize=27",
                    "visionConfiguration.intermediateSize=23",
                    "visionConfiguration.modelType=text",
                    "visionConfiguration.patchSize=25",
                    "visionConfiguration.projectionDimensions=26",
                    "vocabularySize=29",
                ]),
            .init(
                "Paligemma: PaliGemmaProcessorConfiguration",
                MLXVLM.PaliGemmaProcessorConfiguration.self,
                json:
                    #"{"image_mean":[],"image_seq_length":16,"image_std":[],"size":{"height":15,"width":14}}"#,
                requiredKeys: [
                    "image_mean", "image_std", "size", "size.width", "size.height",
                    "image_seq_length",
                ],
                fields: [
                    "imageMean=[]",
                    "imageSequenceLength=16",
                    "imageStd=[]",
                    "size.height=15",
                    "size.width=14",
                ]),
            .init(
                "Pixtral: PixtralConfiguration", MLXVLM.PixtralConfiguration.self,
                json:
                    #"{"model_type":"text","text_config":{"hidden_size":13,"intermediate_size":15,"model_type":"text","num_attention_heads":16,"num_hidden_layers":14,"rms_norm_eps":17,"vocab_size":18},"vision_config":{"hidden_size":21,"image_size":26,"intermediate_size":24,"model_type":"text","num_attention_heads":23,"num_hidden_layers":22,"patch_size":25}}"#,
                requiredKeys: [
                    "text_config", "text_config.model_type", "text_config.hidden_size",
                    "text_config.num_hidden_layers", "text_config.intermediate_size",
                    "text_config.num_attention_heads", "text_config.rms_norm_eps",
                    "text_config.vocab_size", "vision_config", "vision_config.model_type",
                    "vision_config.hidden_size", "vision_config.num_hidden_layers",
                    "vision_config.num_attention_heads", "vision_config.intermediate_size",
                    "vision_config.patch_size", "vision_config.image_size", "model_type",
                ],
                fields: [
                    "_ignoreIndex=nil",
                    "_imageTokenId=nil",
                    "_imageTokenIndex=nil",
                    "_visionFeatureLayer=nil",
                    "_visionFeatureSelectStrategy=nil",
                    "_vocabSize=nil",
                    "modelType=text",
                    "textConfig._headDim=nil",
                    "textConfig._maxPositionEmbeddings=nil",
                    "textConfig._numKeyValueHeads=nil",
                    "textConfig._ropeScaling=nil",
                    "textConfig._ropeTheta=nil",
                    "textConfig._ropeTraditional=nil",
                    "textConfig._tieWordEmbeddings=nil",
                    "textConfig._useQkNorm=nil",
                    "textConfig.hiddenSize=13",
                    "textConfig.intermediateSize=15",
                    "textConfig.modelType=text",
                    "textConfig.numAttentionHeads=16",
                    "textConfig.numHiddenLayers=14",
                    "textConfig.rmsNormEps=17.0",
                    "textConfig.vocabSize=18",
                    "visionConfig._headDim=nil",
                    "visionConfig._numChannels=nil",
                    "visionConfig._rmsNormEps=nil",
                    "visionConfig._ropeTheta=nil",
                    "visionConfig.hiddenSize=21",
                    "visionConfig.imageSize=26",
                    "visionConfig.intermediateSize=24",
                    "visionConfig.modelType=text",
                    "visionConfig.numAttentionHeads=23",
                    "visionConfig.numHiddenLayers=22",
                    "visionConfig.patchSize=25",
                ]),
            .init(
                "Pixtral: PixtralProcessorConfiguration", MLXVLM.PixtralProcessorConfiguration.self,
                json:
                    #"{"image_processor":{"image_mean":[],"image_std":[],"patch_size":15,"size":{}},"image_token":"text","patch_size":17}"#,
                requiredKeys: [
                    "image_processor", "image_processor.image_mean", "image_processor.image_std",
                    "image_processor.size", "image_processor.patch_size", "image_token",
                    "patch_size",
                ],
                fields: [
                    "imageBreakToken=nil",
                    "imageEndToken=nil",
                    "imageProcessor.doNormalize=nil",
                    "imageProcessor.doRescale=nil",
                    "imageProcessor.doResize=nil",
                    "imageProcessor.imageMean=[]",
                    "imageProcessor.imageStd=[]",
                    "imageProcessor.patchSize=15",
                    "imageProcessor.rescaleFactor=nil",
                    "imageProcessor.size.height=nil",
                    "imageProcessor.size.longestEdge=nil",
                    "imageProcessor.size.width=nil",
                    "imageToken=text",
                    "patchSize=17",
                ]),
            .init(
                "Pixtral: PixtralTextConfiguration", MLXVLM.PixtralTextConfiguration.self,
                json:
                    #"{"hidden_size":12,"intermediate_size":14,"model_type":"text","num_attention_heads":15,"num_hidden_layers":13,"rms_norm_eps":16,"vocab_size":17}"#,
                requiredKeys: [
                    "model_type", "hidden_size", "num_hidden_layers", "intermediate_size",
                    "num_attention_heads", "rms_norm_eps", "vocab_size",
                ],
                fields: [
                    "_headDim=nil",
                    "_maxPositionEmbeddings=nil",
                    "_numKeyValueHeads=nil",
                    "_ropeScaling=nil",
                    "_ropeTheta=nil",
                    "_ropeTraditional=nil",
                    "_tieWordEmbeddings=nil",
                    "_useQkNorm=nil",
                    "hiddenSize=12",
                    "intermediateSize=14",
                    "modelType=text",
                    "numAttentionHeads=15",
                    "numHiddenLayers=13",
                    "rmsNormEps=16.0",
                    "vocabSize=17",
                ]),
            .init(
                "Pixtral: PixtralVisionConfiguration", MLXVLM.PixtralVisionConfiguration.self,
                json:
                    #"{"hidden_size":12,"image_size":17,"intermediate_size":15,"model_type":"text","num_attention_heads":14,"num_hidden_layers":13,"patch_size":16}"#,
                requiredKeys: [
                    "model_type", "hidden_size", "num_hidden_layers", "num_attention_heads",
                    "intermediate_size", "patch_size", "image_size",
                ],
                fields: [
                    "_headDim=nil",
                    "_numChannels=nil",
                    "_rmsNormEps=nil",
                    "_ropeTheta=nil",
                    "hiddenSize=12",
                    "imageSize=17",
                    "intermediateSize=15",
                    "modelType=text",
                    "numAttentionHeads=14",
                    "numHiddenLayers=13",
                    "patchSize=16",
                ]),
            .init(
                "Qwen25VL: Qwen25VLConfiguration", MLXVLM.Qwen25VLConfiguration.self,
                json:
                    #"{"hidden_size":25,"image_token_id":31,"intermediate_size":27,"max_window_layers":38,"model_type":"text","num_attention_heads":28,"num_hidden_layers":26,"num_key_value_heads":30,"sliding_window":36,"use_sliding_window":false,"video_token_id":32,"vision_config":{"depth":12,"fullatt_block_indexes":[],"hidden_size":13,"intermediate_size":14,"num_heads":16,"out_hidden_size":15,"patch_size":17,"spatial_merge_size":19,"spatial_patch_size":18,"temporal_patch_size":20,"tokens_per_second":23,"window_size":21},"vision_end_token_id":34,"vision_start_token_id":33,"vision_token_id":35,"vocab_size":29}"#,
                requiredKeys: [
                    "vision_config", "vision_config.depth", "vision_config.hidden_size",
                    "vision_config.intermediate_size", "vision_config.out_hidden_size",
                    "vision_config.num_heads", "vision_config.patch_size",
                    "vision_config.spatial_patch_size", "vision_config.spatial_merge_size",
                    "vision_config.temporal_patch_size", "vision_config.window_size",
                    "vision_config.fullatt_block_indexes", "vision_config.tokens_per_second",
                    "model_type", "hidden_size", "num_hidden_layers", "intermediate_size",
                    "num_attention_heads", "vocab_size", "num_key_value_heads", "image_token_id",
                    "video_token_id", "vision_start_token_id", "vision_end_token_id",
                    "vision_token_id", "sliding_window", "use_sliding_window", "max_window_layers",
                ],
                fields: [
                    "baseConfiguration.hiddenSize=25",
                    "baseConfiguration.imageTokenId=31",
                    "baseConfiguration.intermediateSize=27",
                    "baseConfiguration.maxWindowLayers=38",
                    "baseConfiguration.modelType=text",
                    "baseConfiguration.numAttentionHeads=28",
                    "baseConfiguration.numHiddenLayers=26",
                    "baseConfiguration.numKeyValueHeads=30",
                    "baseConfiguration.slidingWindow=36",
                    "baseConfiguration.useSlidingWindow=false",
                    "baseConfiguration.videoTokenId=32",
                    "baseConfiguration.visionEndTokenId=34",
                    "baseConfiguration.visionStartTokenId=33",
                    "baseConfiguration.visionTokenId=35",
                    "baseConfiguration.vocabularySize=29",
                    "textConfiguration._maxPositionEmbeddings=nil",
                    "textConfiguration._rmsNormEps=nil",
                    "textConfiguration._ropeTheta=nil",
                    "textConfiguration._ropeTraditional=nil",
                    "textConfiguration._slidingWindow=36",
                    "textConfiguration._tieWordEmbeddings=nil",
                    "textConfiguration._useSlidingWindow=false",
                    "textConfiguration.attentionHeads=28",
                    "textConfiguration.hiddenLayers=26",
                    "textConfiguration.hiddenSize=25",
                    "textConfiguration.intermediateSize=27",
                    "textConfiguration.kvHeads=30",
                    "textConfiguration.modelType=text",
                    "textConfiguration.ropeScaling=nil",
                    "textConfiguration.vocabularySize=29",
                    "visionConfiguration._hiddenAct=nil",
                    "visionConfiguration._inChans=nil",
                    "visionConfiguration._layerNormEps=nil",
                    "visionConfiguration._skipVision=nil",
                    "visionConfiguration.depth=12",
                    "visionConfiguration.fullattBlockIndexes=[]",
                    "visionConfiguration.hiddenSize=13",
                    "visionConfiguration.intermediateSize=14",
                    "visionConfiguration.numHeads=16",
                    "visionConfiguration.outHiddenSize=15",
                    "visionConfiguration.patchSize=17",
                    "visionConfiguration.spatialMergeSize=19",
                    "visionConfiguration.spatialPatchSize=18",
                    "visionConfiguration.temporalPatchSize=20",
                    "visionConfiguration.tokensPerSecond=23",
                    "visionConfiguration.windowSize=21",
                ]),
            .init(
                "Qwen25VL: Qwen25VLProcessorConfiguration",
                MLXVLM.Qwen25VLProcessorConfiguration.self,
                json:
                    #"{"image_mean":[],"image_processor_type":"text","image_std":[],"max_pixels":14,"merge_size":15,"min_pixels":13,"patch_size":16,"temporal_patch_size":17}"#,
                requiredKeys: [
                    "image_mean", "image_std", "min_pixels", "max_pixels", "merge_size",
                    "patch_size", "temporal_patch_size", "image_processor_type",
                ],
                fields: [
                    "imageMean=[]",
                    "imageProcessorType=text",
                    "imageStd=[]",
                    "maxPixels=14",
                    "mergeSize=15",
                    "minPixels=13",
                    "patchSize=16",
                    "temporalPatchSize=17",
                ]),
            .init(
                "Qwen2VL: Qwen2VLConfiguration", MLXVLM.Qwen2VLConfiguration.self,
                json:
                    #"{"hidden_size":22,"image_token_id":28,"intermediate_size":24,"model_type":"text","num_attention_heads":25,"num_hidden_layers":23,"num_key_value_heads":27,"video_token_id":29,"vision_config":{"depth":12,"embed_dim":13,"hidden_size":14,"mlp_ratio":17,"num_heads":15,"patch_size":16,"spatial_merge_size":19,"spatial_patch_size":18,"temporal_patch_size":20},"vocab_size":26}"#,
                requiredKeys: [
                    "vision_config", "vision_config.depth", "vision_config.embed_dim",
                    "vision_config.hidden_size", "vision_config.num_heads",
                    "vision_config.patch_size", "vision_config.mlp_ratio",
                    "vision_config.spatial_patch_size", "vision_config.spatial_merge_size",
                    "vision_config.temporal_patch_size", "model_type", "hidden_size",
                    "num_hidden_layers", "intermediate_size", "num_attention_heads", "vocab_size",
                    "num_key_value_heads", "image_token_id", "video_token_id",
                ],
                fields: [
                    "baseConfiguration.hiddenSize=22",
                    "baseConfiguration.imageTokenId=28",
                    "baseConfiguration.modelType=text",
                    "baseConfiguration.videoTokenId=29",
                    "baseConfiguration.vocabularySize=26",
                    "textConfiguration._maxPositionEmbeddings=nil",
                    "textConfiguration._rmsNormEps=nil",
                    "textConfiguration._ropeTheta=nil",
                    "textConfiguration._ropeTraditional=nil",
                    "textConfiguration._tieWordEmbeddings=nil",
                    "textConfiguration.attentionHeads=25",
                    "textConfiguration.hiddenLayers=23",
                    "textConfiguration.hiddenSize=22",
                    "textConfiguration.intermediateSize=24",
                    "textConfiguration.kvHeads=27",
                    "textConfiguration.modelType=text",
                    "textConfiguration.ropeScaling=nil",
                    "textConfiguration.vocabularySize=26",
                    "visionConfiguration._inChannels=nil",
                    "visionConfiguration._layerNormEps=nil",
                    "visionConfiguration.depth=12",
                    "visionConfiguration.embedDimensions=13",
                    "visionConfiguration.hiddenSize=14",
                    "visionConfiguration.mlpRatio=17.0",
                    "visionConfiguration.numHeads=15",
                    "visionConfiguration.patchSize=16",
                    "visionConfiguration.spatialMergeSize=19",
                    "visionConfiguration.spatialPatchSize=18",
                    "visionConfiguration.temporalPatchSize=20",
                ]),
            .init(
                "Qwen2VL: Qwen2VLProcessorConfiguration", MLXVLM.Qwen2VLProcessorConfiguration.self,
                json:
                    #"{"image_mean":[],"image_std":[],"merge_size":13,"patch_size":14,"temporal_patch_size":15}"#,
                requiredKeys: [
                    "image_mean", "image_std", "merge_size", "patch_size", "temporal_patch_size",
                ],
                fields: [
                    "_maxPixels=nil",
                    "_minPixels=nil",
                    "_size=nil",
                    "imageMean=[]",
                    "imageStd=[]",
                    "mergeSize=13",
                    "patchSize=14",
                    "temporalPatchSize=15",
                ]),
            .init(
                "Qwen35: Qwen35Configuration", MLXVLM.Qwen35Configuration.self,
                json:
                    #"{"model_type":"text","text_config":{},"vision_config":{"depth":14,"hidden_size":15,"intermediate_size":16,"model_type":"text","num_heads":18,"num_position_embeddings":22,"out_hidden_size":17,"patch_size":19,"spatial_merge_size":20,"temporal_patch_size":21}}"#,
                requiredKeys: [
                    "text_config", "vision_config", "vision_config.model_type",
                    "vision_config.depth", "vision_config.hidden_size",
                    "vision_config.intermediate_size", "vision_config.out_hidden_size",
                    "vision_config.num_heads", "vision_config.patch_size",
                    "vision_config.spatial_merge_size", "vision_config.temporal_patch_size",
                    "vision_config.num_position_embeddings", "model_type",
                ],
                fields: [
                    "_eosTokenId=nil",
                    "_ignoreIndex=nil",
                    "_imageTokenId=nil",
                    "_imageTokenIndex=nil",
                    "_videoTokenId=nil",
                    "_videoTokenIndex=nil",
                    "_visionEndTokenId=nil",
                    "_visionStartTokenId=nil",
                    "_vocabSize=nil",
                    "modelType=text",
                    "textConfiguration.attentionBias=false",
                    "textConfiguration.attentionHeads=32",
                    "textConfiguration.decoderSparseStep=1",
                    "textConfiguration.fullAttentionInterval=4",
                    "textConfiguration.headDim=128",
                    "textConfiguration.hiddenLayers=32",
                    "textConfiguration.hiddenSize=4096",
                    "textConfiguration.intermediateSize=14336",
                    "textConfiguration.kvHeads=8",
                    "textConfiguration.linearConvKernelDim=4",
                    "textConfiguration.linearKeyHeadDim=192",
                    "textConfiguration.linearNumKeyHeads=16",
                    "textConfiguration.linearNumValueHeads=64",
                    "textConfiguration.linearValueHeadDim=128",
                    "textConfiguration.maxPositionEmbeddings=131072",
                    "textConfiguration.modelType=",
                    "textConfiguration.moeIntermediateSize=0",
                    "textConfiguration.normTopkProb=true",
                    "textConfiguration.numExperts=0",
                    "textConfiguration.numExpertsPerTok=0",
                    "textConfiguration.partialRotaryFactor=0.25",
                    "textConfiguration.rmsNormEps=1e-06",
                    "textConfiguration.ropeParameters[mrope_section]=ints([11, 11, 10])",
                    "textConfiguration.ropeParameters[partial_rotary_factor]=float(0.25)",
                    "textConfiguration.ropeParameters[rope_theta]=float(100000.0)",
                    #"textConfiguration.ropeParameters[type]=string("default")"#,
                    "textConfiguration.ropeTheta=100000.0",
                    "textConfiguration.sharedExpertIntermediateSize=0",
                    "textConfiguration.tieWordEmbeddings=false",
                    "textConfiguration.vocabularySize=248320",
                    "visionConfiguration._deepstackVisualIndexes=nil",
                    "visionConfiguration._hiddenAct=nil",
                    "visionConfiguration._inChannels=nil",
                    "visionConfiguration.depth=14",
                    "visionConfiguration.hiddenSize=15",
                    "visionConfiguration.intermediateSize=16",
                    "visionConfiguration.modelType=text",
                    "visionConfiguration.numHeads=18",
                    "visionConfiguration.numPositionEmbeddings=22",
                    "visionConfiguration.outHiddenSize=17",
                    "visionConfiguration.patchSize=19",
                    "visionConfiguration.spatialMergeSize=20",
                    "visionConfiguration.temporalPatchSize=21",
                ]),
            .init(
                "Qwen3VL: Qwen3VLConfiguration", MLXVLM.Qwen3VLConfiguration.self,
                json:
                    #"{"model_type":"text","text_config":{"head_dim":17,"hidden_size":13,"intermediate_size":14,"max_position_embeddings":18,"model_type":"text","num_attention_heads":16,"num_hidden_layers":15,"vocab_size":19},"vision_config":{"depth":22,"hidden_size":23,"intermediate_size":24,"model_type":"text","num_heads":26,"num_position_embeddings":30,"out_hidden_size":25,"patch_size":27,"spatial_merge_size":28,"temporal_patch_size":29}}"#,
                requiredKeys: [
                    "text_config", "text_config.model_type", "text_config.hidden_size",
                    "text_config.intermediate_size", "text_config.num_hidden_layers",
                    "text_config.num_attention_heads", "text_config.head_dim",
                    "text_config.max_position_embeddings", "text_config.vocab_size",
                    "vision_config", "vision_config.model_type", "vision_config.depth",
                    "vision_config.hidden_size", "vision_config.intermediate_size",
                    "vision_config.out_hidden_size", "vision_config.num_heads",
                    "vision_config.patch_size", "vision_config.spatial_merge_size",
                    "vision_config.temporal_patch_size", "vision_config.num_position_embeddings",
                    "model_type",
                ],
                fields: [
                    "_eosTokenId=nil",
                    "_ignoreIndex=nil",
                    "_imageTokenId=nil",
                    "_imageTokenIndex=nil",
                    "_videoTokenId=nil",
                    "_videoTokenIndex=nil",
                    "_visionEndTokenId=nil",
                    "_visionStartTokenId=nil",
                    "_visionTokenId=nil",
                    "_vocabSize=nil",
                    "modelType=text",
                    "textConfiguration._attentionBias=nil",
                    "textConfiguration._decoderSparseStep=nil",
                    "textConfiguration._hiddenAct=nil",
                    "textConfiguration._mlpOnlyLayers=nil",
                    "textConfiguration._moeIntermediateSize=nil",
                    "textConfiguration._normTopKProb=nil",
                    "textConfiguration._numExperts=nil",
                    "textConfiguration._numExpertsPerTok=nil",
                    "textConfiguration._numKeyValueHeads=nil",
                    "textConfiguration._rmsNormEps=nil",
                    "textConfiguration._ropeScaling=nil",
                    "textConfiguration._ropeTheta=nil",
                    "textConfiguration._tieWordEmbeddings=nil",
                    "textConfiguration.headDim=17",
                    "textConfiguration.hiddenSize=13",
                    "textConfiguration.intermediateSize=14",
                    "textConfiguration.maxPositionEmbeddings=18",
                    "textConfiguration.modelType=text",
                    "textConfiguration.numAttentionHeads=16",
                    "textConfiguration.numHiddenLayers=15",
                    "textConfiguration.vocabSize=19",
                    "visionConfiguration._deepstackVisualIndexes=nil",
                    "visionConfiguration._hiddenAct=nil",
                    "visionConfiguration._inChannels=nil",
                    "visionConfiguration.depth=22",
                    "visionConfiguration.hiddenSize=23",
                    "visionConfiguration.intermediateSize=24",
                    "visionConfiguration.modelType=text",
                    "visionConfiguration.numHeads=26",
                    "visionConfiguration.numPositionEmbeddings=30",
                    "visionConfiguration.outHiddenSize=25",
                    "visionConfiguration.patchSize=27",
                    "visionConfiguration.spatialMergeSize=28",
                    "visionConfiguration.temporalPatchSize=29",
                ]),
            .init(
                "Qwen3VL: Qwen3VLProcessorConfiguration", MLXVLM.Qwen3VLProcessorConfiguration.self,
                json:
                    #"{"image_mean":[],"image_processor_type":"text","image_std":[],"merge_size":13,"patch_size":14,"temporal_patch_size":15}"#,
                requiredKeys: [
                    "image_mean", "image_std", "merge_size", "patch_size", "temporal_patch_size",
                    "image_processor_type",
                ],
                fields: [
                    "_maxPixels=nil",
                    "_minPixels=nil",
                    "imageMean=[]",
                    "imageProcessorType=text",
                    "imageStd=[]",
                    "mergeSize=13",
                    "patchSize=14",
                    "temporalPatchSize=15",
                ]),
            .init(
                "Qwen4Exp: Qwen4ExpVLMConfiguration", MLXVLM.Qwen4ExpVLMConfiguration.self,
                json: "{}",
                requiredKeys: [],
                fields: [
                    "_imageTokenId=nil",
                    "_imageTokenIndex=nil",
                    "_videoTokenId=nil",
                    "_videoTokenIndex=nil",
                    "_visionEndTokenId=nil",
                    "_visionStartTokenId=nil",
                    "languageModelOnly=false",
                    "text.imageTokenId=nil",
                    "text.modelType=qwen4_exp",
                    "text.textConfig.attentionBias=false",
                    "text.textConfig.attentionHeads=24",
                    "text.textConfig.eosTokenId=[]",
                    "text.textConfig.fullAttentionInterval=4",
                    "text.textConfig.hcCount=4",
                    "text.textConfig.hcLowrank=320",
                    "text.textConfig.headDim=256",
                    "text.textConfig.headsPerNgram=8",
                    "text.textConfig.hiddenLayers=48",
                    "text.textConfig.hiddenSize=2560",
                    "text.textConfig.indexerBudget=2048",
                    "text.textConfig.indexerCompressRatio=4",
                    "text.textConfig.indexerHeadDim=128",
                    "text.textConfig.indexerKVHeads=1",
                    "text.textConfig.indexerNHeads=4",
                    "text.textConfig.kvHeads=2",
                    "text.textConfig.layerTypes[0]=linear_attention",
                    "text.textConfig.layerTypes[10]=linear_attention",
                    "text.textConfig.layerTypes[11]=qwen_sparse_attention",
                    "text.textConfig.layerTypes[12]=linear_attention",
                    "text.textConfig.layerTypes[13]=linear_attention",
                    "text.textConfig.layerTypes[14]=linear_attention",
                    "text.textConfig.layerTypes[15]=qwen_sparse_attention",
                    "text.textConfig.layerTypes[16]=linear_attention",
                    "text.textConfig.layerTypes[17]=linear_attention",
                    "text.textConfig.layerTypes[18]=linear_attention",
                    "text.textConfig.layerTypes[19]=qwen_sparse_attention",
                    "text.textConfig.layerTypes[1]=linear_attention",
                    "text.textConfig.layerTypes[20]=linear_attention",
                    "text.textConfig.layerTypes[21]=linear_attention",
                    "text.textConfig.layerTypes[22]=linear_attention",
                    "text.textConfig.layerTypes[23]=qwen_sparse_attention",
                    "text.textConfig.layerTypes[24]=linear_attention",
                    "text.textConfig.layerTypes[25]=linear_attention",
                    "text.textConfig.layerTypes[26]=linear_attention",
                    "text.textConfig.layerTypes[27]=qwen_sparse_attention",
                    "text.textConfig.layerTypes[28]=linear_attention",
                    "text.textConfig.layerTypes[29]=linear_attention",
                    "text.textConfig.layerTypes[2]=linear_attention",
                    "text.textConfig.layerTypes[30]=linear_attention",
                    "text.textConfig.layerTypes[31]=qwen_sparse_attention",
                    "text.textConfig.layerTypes[32]=linear_attention",
                    "text.textConfig.layerTypes[33]=linear_attention",
                    "text.textConfig.layerTypes[34]=linear_attention",
                    "text.textConfig.layerTypes[35]=qwen_sparse_attention",
                    "text.textConfig.layerTypes[36]=linear_attention",
                    "text.textConfig.layerTypes[37]=linear_attention",
                    "text.textConfig.layerTypes[38]=linear_attention",
                    "text.textConfig.layerTypes[39]=qwen_sparse_attention",
                    "text.textConfig.layerTypes[3]=qwen_sparse_attention",
                    "text.textConfig.layerTypes[40]=linear_attention",
                    "text.textConfig.layerTypes[41]=linear_attention",
                    "text.textConfig.layerTypes[42]=linear_attention",
                    "text.textConfig.layerTypes[43]=qwen_sparse_attention",
                    "text.textConfig.layerTypes[44]=linear_attention",
                    "text.textConfig.layerTypes[45]=linear_attention",
                    "text.textConfig.layerTypes[46]=linear_attention",
                    "text.textConfig.layerTypes[47]=qwen_sparse_attention",
                    "text.textConfig.layerTypes[4]=linear_attention",
                    "text.textConfig.layerTypes[5]=linear_attention",
                    "text.textConfig.layerTypes[6]=linear_attention",
                    "text.textConfig.layerTypes[7]=qwen_sparse_attention",
                    "text.textConfig.layerTypes[8]=linear_attention",
                    "text.textConfig.layerTypes[9]=linear_attention",
                    "text.textConfig.linearConvKernelDim=4",
                    "text.textConfig.linearKeyHeadDim=128",
                    "text.textConfig.linearNumKeyHeads=16",
                    "text.textConfig.linearNumValueHeads=48",
                    "text.textConfig.linearValueHeadDim=128",
                    "text.textConfig.makeNgramVocabSizeDivisibleBy=128",
                    "text.textConfig.maxPositionEmbeddings=262144",
                    "text.textConfig.modelType=qwen4_exp_text",
                    "text.textConfig.moeIntermediateSize=640",
                    "text.textConfig.mropeSection[0]=11",
                    "text.textConfig.mropeSection[1]=11",
                    "text.textConfig.mropeSection[2]=10",
                    "text.textConfig.mtpNumHiddenLayers=0",
                    "text.textConfig.ngramSize=3",
                    "text.textConfig.ngramVocabSizeBase=20000000",
                    "text.textConfig.normTopkProb=true",
                    "text.textConfig.numExperts=512",
                    "text.textConfig.numExpertsPerTok=10",
                    "text.textConfig.outputGateType=sigmoid",
                    "text.textConfig.partialRotaryFactor=0.25",
                    "text.textConfig.pleConvKernelSize=4",
                    "text.textConfig.pleEmbedDim=2560",
                    "text.textConfig.pleLayerIds=[]",
                    "text.textConfig.rmsNormEps=1e-06",
                    "text.textConfig.ropeTheta=10000000.0",
                    "text.textConfig.seed=1234",
                    "text.textConfig.sharedExpertIntermediateSize=640",
                    "text.textConfig.splitNgramParts=128",
                    "text.textConfig.tieWordEmbeddings=false",
                    "text.textConfig.vocabularySize=248320",
                    "text.videoTokenId=nil",
                    "visionConfiguration=nil",
                ]),
            .init(
                "Qwen4ExpVideoConfiguration: Qwen4ExpVideoConfiguration",
                MLXVLM.Qwen4ExpVideoConfiguration.self,
                json: "{}",
                requiredKeys: [],
                fields: [
                    "fps=2.0",
                    "imageMean[0]=0.5",
                    "imageMean[1]=0.5",
                    "imageMean[2]=0.5",
                    "imageStd[0]=0.5",
                    "imageStd[1]=0.5",
                    "imageStd[2]=0.5",
                    "maxFrames=768",
                    "mergeSize=2",
                    "minFrames=4",
                    "patchSize=16",
                    "size.longestEdge=786432",
                    "size.shortestEdge=131072",
                    "temporalPatchSize=2",
                ]),
            .init(
                "SmolVLM2: SmolVLMProcessorConfiguration",
                MLXVLM.SmolVLMProcessorConfiguration.self,
                json:
                    #"{"image_mean":[],"image_std":[],"max_image_size":{"longest_edge":16},"size":{"longest_edge":14},"video_sampling":{"fps":18,"max_frames":19}}"#,
                requiredKeys: [
                    "image_mean", "image_std", "size", "size.longest_edge", "max_image_size",
                    "max_image_size.longest_edge", "video_sampling", "video_sampling.fps",
                    "video_sampling.max_frames",
                ],
                fields: [
                    "_imageSequenceLength=nil",
                    "imageMean=[]",
                    "imageStd=[]",
                    "maxImageSize.longestEdge=16",
                    "size.longestEdge=14",
                    "videoSampling.fps=18",
                    "videoSampling.maxFrames=19",
                ]),
        ]

        @Test(arguments: cases)
        func minimalJSONGivesTheFields(_ configuration: ConfigurationDecodingCase) throws {
            try configuration.expectMinimalJSONGivesTheFields()
        }

        @Test(arguments: cases)
        func eachRequiredKeyIsRequired(_ configuration: ConfigurationDecodingCase) throws {
            try configuration.expectEachRequiredKeyIsRequired()
        }

        @Test(arguments: cases)
        func aNonObjectRootIsRejected(_ configuration: ConfigurationDecodingCase) {
            configuration.expectANonObjectRootIsRejected()
        }
    }
}
