import Foundation
import Testing

@testable import MLXVLM

extension UnitTests {
    /// Configurations of `MLXVLM` decoded from a JSON that sets each key,
    /// also the optional keys, to a value that is not the default. The
    /// expected lines were written by hand from the JSON and the `CodingKeys`
    /// of each type.
    enum VLMFullKeyCases {
        static let all: [ConfigurationDecodingCase] = [
            .init(
                "Gemma3: Gemma3Configuration", MLXVLM.Gemma3Configuration.self,
                json:
                    #"{"mm_tokens_per_image":1421,"model_type":"gemma3_custom","pad_token_id":1423,"quantization":{"bits":4,"group_size":32,"mode":"mxfp4"},"text_config":{"final_logit_softcapping":2.5,"head_dim":1407,"hidden_size":1401,"intermediate_size":1403,"model_type":"gemma3_custom_text","num_attention_heads":1405,"num_hidden_layers":1402,"num_key_value_heads":1406,"query_pre_attn_scalar":3.5,"rope_scaling":{"factor":1.5},"sliding_window":1404},"vision_config":{"hidden_size":1412,"image_size":1416,"intermediate_size":1413,"model_type":"siglip_custom","num_attention_heads":1414,"num_hidden_layers":1411,"patch_size":1415},"vocab_size":1422}"#,
                requiredKeys: [],
                fields: [
                    "_padTokenId=1423",
                    "_vocabularySize=1422",
                    "mmTokensPerImage=1421",
                    "modelType=gemma3_custom",
                    "quantization._mode=mxfp4",
                    "quantization.bits=4",
                    "quantization.groupSize=32",
                    "textConfiguration._attentionHeads=1405",
                    "textConfiguration._headDim=1407",
                    "textConfiguration._kvHeads=1406",
                    "textConfiguration._queryPreAttnScalar=3.5",
                    "textConfiguration.finalLogitSoftcapping=2.5",
                    "textConfiguration.hiddenLayers=1402",
                    "textConfiguration.hiddenSize=1401",
                    "textConfiguration.intermediateSize=1403",
                    "textConfiguration.maxPositionEmbeddings=4096",
                    "textConfiguration.mmTokensPerImage=256",
                    "textConfiguration.modelType=gemma3_custom_text",
                    "textConfiguration.rmsNormEps=1e-06",
                    "textConfiguration.ropeLocalBaseFreq=10000.0",
                    "textConfiguration.ropeScaling[factor]=float(1.5)",
                    "textConfiguration.ropeTheta=1000000.0",
                    "textConfiguration.ropeTraditional=false",
                    "textConfiguration.slidingWindow=1404",
                    "textConfiguration.slidingWindowPattern=6",
                    "textConfiguration.vocabularySize=262208",
                    "visionConfiguration.attentionHeads=1414",
                    "visionConfiguration.hiddenLayers=1411",
                    "visionConfiguration.hiddenSize=1412",
                    "visionConfiguration.imageSize=1416",
                    "visionConfiguration.intermediateSize=1413",
                    "visionConfiguration.layerNormEps=1e-06",
                    "visionConfiguration.modelType=siglip_custom",
                    "visionConfiguration.numChannels=3",
                    "visionConfiguration.patchSize=1415",
                ]),
            .init(
                "Gemma4: Gemma4Configuration", MLXVLM.Gemma4Configuration.self,
                json:
                    #"{"image_token_id":531,"model_type":"gemma4_custom_vlm","quantization":{"bits":6,"group_size":128,"mode":"mxfp8","vision_tower.x":false},"text_config":{"attention_k_eq_v":true,"enable_moe_block":true,"final_logit_softcapping":12.5,"global_head_dim":405,"global_partial_rotary_factor":0.625,"head_dim":404,"hidden_size":401,"hidden_size_per_layer_input":411,"intermediate_size":402,"layer_types":["full_attention","sliding_attention","full_attention","sliding_attention"],"max_position_embeddings":414,"model_type":"gemma4_custom_text","moe_intermediate_size":417,"num_attention_heads":403,"num_experts":415,"num_global_key_value_heads":409,"num_hidden_layers":3,"num_key_value_heads":408,"num_kv_shared_layers":410,"rms_norm_eps":0.125,"rope_parameters":{"full_attention":{"partial_rotary_factor":0.375,"rope_theta":2.5},"sliding_attention":{"rope_theta":1.5}},"sliding_window":412,"sliding_window_pattern":413,"tie_word_embeddings":false,"top_k_experts":416,"use_bidirectional_attention":"vision","use_double_wide_mlp":false,"vocab_size":406,"vocab_size_per_layer_input":407},"video_token_id":532,"vision_config":{"default_output_length":509,"head_dim":506,"hidden_size":501,"intermediate_size":502,"num_attention_heads":504,"num_hidden_layers":503,"num_key_value_heads":505,"patch_size":507,"pooling_kernel_size":510,"position_embedding_size":508,"rms_norm_eps":0.25,"rope_parameters":{"rope_theta":3.5},"standardize":true,"use_clipped_linears":false},"vision_soft_tokens_per_image":533}"#,
                requiredKeys: [],
                fields: [
                    "imageTokenId=531",
                    "modelType=gemma4_custom_vlm",
                    "quantization._mode=mxfp8",
                    "quantization.bits=6",
                    "quantization.groupSize=128",
                    "textConfig.attentionKeqV=true",
                    "textConfig.enableMoeBlock=true",
                    "textConfig.finalLogitSoftcapping=12.5",
                    "textConfig.fullPartialRotaryFactor=0.375",
                    "textConfig.fullRopeTheta=2.5",
                    "textConfig.globalHeadDim=405",
                    "textConfig.globalPartialRotaryFactor=0.625",
                    "textConfig.headDim=404",
                    "textConfig.hiddenSize=401",
                    "textConfig.hiddenSizePerLayerInput=411",
                    "textConfig.intermediateSize=402",
                    "textConfig.layerTypes[0]=full_attention",
                    "textConfig.layerTypes[1]=sliding_attention",
                    "textConfig.layerTypes[2]=full_attention",
                    "textConfig.maxPositionEmbeddings=414",
                    "textConfig.modelType=gemma4_custom_text",
                    "textConfig.moeIntermediateSize=417",
                    "textConfig.numAttentionHeads=403",
                    "textConfig.numExperts=415",
                    "textConfig.numGlobalKeyValueHeads=409",
                    "textConfig.numHiddenLayers=3",
                    "textConfig.numKeyValueHeads=408",
                    "textConfig.numKvSharedLayers=410",
                    "textConfig.perLayerQuantization.perLayerQuantization[vision_tower.x]=skip",
                    "textConfig.perLayerQuantization.quantization._mode=mxfp8",
                    "textConfig.perLayerQuantization.quantization.bits=6",
                    "textConfig.perLayerQuantization.quantization.groupSize=128",
                    "textConfig.quantizationBits=6",
                    "textConfig.quantizationGroupSize=128",
                    "textConfig.quantizationMode=mxfp8",
                    "textConfig.rmsNormEps=0.125",
                    "textConfig.ropeParameters[full_attention][partial_rotary_factor]=float(0.375)",
                    "textConfig.ropeParameters[full_attention][rope_theta]=float(2.5)",
                    "textConfig.ropeParameters[sliding_attention][rope_theta]=float(1.5)",
                    "textConfig.slidingRopeTheta=1.5",
                    "textConfig.slidingWindow=412",
                    "textConfig.slidingWindowPattern=413",
                    "textConfig.tieWordEmbeddings=false",
                    "textConfig.topKExperts=416",
                    "textConfig.useBidirectionalAttention=vision",
                    "textConfig.useDoubleWideMlp=false",
                    "textConfig.vocabSize=406",
                    "textConfig.vocabSizePerLayerInput=407",
                    "videoTokenId=532",
                    "visionConfig.defaultOutputLength=509",
                    "visionConfig.headDim=506",
                    "visionConfig.hiddenSize=501",
                    "visionConfig.intermediateSize=502",
                    "visionConfig.numAttentionHeads=504",
                    "visionConfig.numHiddenLayers=503",
                    "visionConfig.numKeyValueHeads=505",
                    "visionConfig.patchSize=507",
                    "visionConfig.poolingKernelSize=510",
                    "visionConfig.positionEmbeddingSize=508",
                    "visionConfig.rmsNormEps=0.25",
                    "visionConfig.ropeTheta=3.5",
                    "visionConfig.standardize=true",
                    "visionConfig.useClippedLinears=false",
                    "visionSoftTokensPerImage=533",
                ]),
            .init(
                "Gemma4: Gemma4ProcessorConfiguration", MLXVLM.Gemma4ProcessorConfiguration.self,
                json:
                    #"{"audio_seq_length":526,"boi_token_id":527,"eoi_token_id":528,"image_seq_length":525,"max_soft_tokens":522,"patch_size":521,"pooling_kernel_size":524,"processor_class":"CustomProcessor","video_processor":{"max_soft_tokens":523}}"#,
                requiredKeys: [],
                fields: [
                    "audioSeqLength=526",
                    "boiTokenId=527",
                    "eoiTokenId=528",
                    "imageSeqLength=525",
                    "maxSoftTokens=522",
                    "patchSize=521",
                    "poolingKernelSize=524",
                    "processorClass=CustomProcessor",
                    "videoMaxSoftTokens=523",
                ]),
            .init(
                "Gemma4: Gemma4VisionConfig", MLXVLM.Gemma4VisionConfig.self,
                json:
                    #"{"default_output_length":509,"head_dim":506,"hidden_size":501,"intermediate_size":502,"num_attention_heads":504,"num_hidden_layers":503,"num_key_value_heads":505,"patch_size":507,"pooling_kernel_size":510,"position_embedding_size":508,"rms_norm_eps":0.25,"rope_parameters":{"rope_theta":3.5},"standardize":true,"use_clipped_linears":false}"#,
                requiredKeys: [],
                fields: [
                    "defaultOutputLength=509",
                    "headDim=506",
                    "hiddenSize=501",
                    "intermediateSize=502",
                    "numAttentionHeads=504",
                    "numHiddenLayers=503",
                    "numKeyValueHeads=505",
                    "patchSize=507",
                    "poolingKernelSize=510",
                    "positionEmbeddingSize=508",
                    "rmsNormEps=0.25",
                    "ropeTheta=3.5",
                    "standardize=true",
                    "useClippedLinears=false",
                ]),
            .init(
                "LFM2VL: LFM2VLProcessorConfiguration", MLXVLM.LFM2VLProcessorConfiguration.self,
                json:
                    #"{"downsample_factor":804,"encoder_patch_size":802,"image_mean":[0.25,0.375,0.625],"image_std":[0.125,0.75,0.875],"max_tiles":803,"tile_size":801}"#,
                requiredKeys: [],
                fields: [
                    "_downsampleFactor=804",
                    "_encoderPatchSize=802",
                    "_imageMean[0]=0.25",
                    "_imageMean[1]=0.375",
                    "_imageMean[2]=0.625",
                    "_imageStd[0]=0.125",
                    "_imageStd[1]=0.75",
                    "_imageStd[2]=0.875",
                    "_maxTiles=803",
                    "_tileSize=801",
                ]),
            .init(
                "Qwen3VL: Qwen3VLConfiguration", MLXVLM.Qwen3VLConfiguration.self,
                json:
                    #"{"eos_token_id":[1529,1530],"ignore_index":-7,"image_token_id":1521,"image_token_index":1523,"model_type":"qwen3_vl_custom","text_config":{"attention_bias":true,"decoder_sparse_step":1512,"head_dim":1506,"hidden_act":"text_act_c","hidden_size":1501,"intermediate_size":1502,"max_position_embeddings":1507,"mlp_only_layers":[1513],"model_type":"qwen3_vl_custom_text","moe_intermediate_size":1514,"norm_topk_prob":false,"num_attention_heads":1504,"num_experts":1510,"num_experts_per_tok":1511,"num_hidden_layers":1503,"num_key_value_heads":1505,"rms_norm_eps":0.25,"rope_scaling":{"mrope_interleaved":true,"mrope_section":[1508,1509],"type":"mrope"},"rope_theta":1.5,"tie_word_embeddings":false,"vocab_size":1515},"video_token_id":1522,"video_token_index":1524,"vision_config":{"deepstack_visual_indexes":[211,212],"depth":201,"hidden_act":"vision_act_b","hidden_size":202,"in_channels":210,"intermediate_size":203,"model_type":"vision_model_a","num_heads":205,"num_position_embeddings":209,"out_hidden_size":204,"patch_size":206,"spatial_merge_size":207,"temporal_patch_size":208},"vision_end_token_id":1526,"vision_start_token_id":1525,"vision_token_id":1527,"vocab_size":1528}"#,
                requiredKeys: [],
                fields: [
                    "_eosTokenId[0]=1529",
                    "_eosTokenId[1]=1530",
                    "_ignoreIndex=-7",
                    "_imageTokenId=1521",
                    "_imageTokenIndex=1523",
                    "_videoTokenId=1522",
                    "_videoTokenIndex=1524",
                    "_visionEndTokenId=1526",
                    "_visionStartTokenId=1525",
                    "_visionTokenId=1527",
                    "_vocabSize=1528",
                    "modelType=qwen3_vl_custom",
                    "textConfiguration._attentionBias=true",
                    "textConfiguration._decoderSparseStep=1512",
                    "textConfiguration._hiddenAct=text_act_c",
                    "textConfiguration._mlpOnlyLayers[0]=1513",
                    "textConfiguration._moeIntermediateSize=1514",
                    "textConfiguration._normTopKProb=false",
                    "textConfiguration._numExperts=1510",
                    "textConfiguration._numExpertsPerTok=1511",
                    "textConfiguration._numKeyValueHeads=1505",
                    "textConfiguration._rmsNormEps=0.25",
                    "textConfiguration._ropeScaling.mropeInterleaved=true",
                    "textConfiguration._ropeScaling.mropeSection[0]=1508",
                    "textConfiguration._ropeScaling.mropeSection[1]=1509",
                    "textConfiguration._ropeScaling.type=mrope",
                    "textConfiguration._ropeTheta=1.5",
                    "textConfiguration._tieWordEmbeddings=false",
                    "textConfiguration.headDim=1506",
                    "textConfiguration.hiddenSize=1501",
                    "textConfiguration.intermediateSize=1502",
                    "textConfiguration.maxPositionEmbeddings=1507",
                    "textConfiguration.modelType=qwen3_vl_custom_text",
                    "textConfiguration.numAttentionHeads=1504",
                    "textConfiguration.numHiddenLayers=1503",
                    "textConfiguration.vocabSize=1515",
                    "visionConfiguration._deepstackVisualIndexes[0]=211",
                    "visionConfiguration._deepstackVisualIndexes[1]=212",
                    "visionConfiguration._hiddenAct=vision_act_b",
                    "visionConfiguration._inChannels=210",
                    "visionConfiguration.depth=201",
                    "visionConfiguration.hiddenSize=202",
                    "visionConfiguration.intermediateSize=203",
                    "visionConfiguration.modelType=vision_model_a",
                    "visionConfiguration.numHeads=205",
                    "visionConfiguration.numPositionEmbeddings=209",
                    "visionConfiguration.outHiddenSize=204",
                    "visionConfiguration.patchSize=206",
                    "visionConfiguration.spatialMergeSize=207",
                    "visionConfiguration.temporalPatchSize=208",
                ]),
            .init(
                "Qwen4Exp: Qwen4ExpVLMConfiguration", MLXVLM.Qwen4ExpVLMConfiguration.self,
                json:
                    #"{"image_token_id":140,"image_token_index":221,"language_model_only":true,"model_type":"qwen4_custom","text_config":{"attention_bias":true,"eos_token_id":[132,133],"full_attention_interval":113,"hc_count":114,"hc_lowrank":115,"head_dim":105,"heads_per_ngram":119,"hidden_size":101,"indexer_budget":126,"indexer_compress_ratio":127,"indexer_head_dim":125,"indexer_kv_heads":124,"indexer_n_heads":123,"layer_types":["full_attention","linear_attention"],"linear_conv_kernel_dim":110,"linear_key_head_dim":108,"linear_num_key_heads":107,"linear_num_value_heads":106,"linear_value_head_dim":109,"make_ngram_vocab_size_divisible_by":121,"max_position_embeddings":112,"model_type":"qwen4_custom_text","moe_intermediate_size":131,"mtp_num_hidden_layers":134,"ngram_size":118,"ngram_vocab_size_base":120,"norm_topk_prob":false,"num_attention_heads":103,"num_experts":128,"num_experts_per_tok":129,"num_hidden_layers":2,"num_key_value_heads":104,"output_gate_type":"silu","ple_conv_kernel_size":117,"ple_embed_dim":116,"ple_layer_ids":[1,2],"rms_norm_eps":0.5,"rope_parameters":{"mrope_section":[3,4,5],"partial_rotary_factor":0.75,"rope_theta":2.5},"seed":135,"shared_expert_intermediate_size":130,"split_ngram_parts":122,"tie_word_embeddings":true,"vocab_size":111},"video_token_id":141,"video_token_index":222,"vision_config":{"deepstack_visual_indexes":[211,212],"depth":201,"hidden_act":"vision_act_b","hidden_size":202,"in_channels":210,"intermediate_size":203,"model_type":"vision_model_a","num_heads":205,"num_position_embeddings":209,"out_hidden_size":204,"patch_size":206,"spatial_merge_size":207,"temporal_patch_size":208},"vision_end_token_id":224,"vision_start_token_id":223}"#,
                requiredKeys: [],
                fields: [
                    "_imageTokenId=140",
                    "_imageTokenIndex=221",
                    "_videoTokenId=141",
                    "_videoTokenIndex=222",
                    "_visionEndTokenId=224",
                    "_visionStartTokenId=223",
                    "languageModelOnly=true",
                    "text.imageTokenId=140",
                    "text.modelType=qwen4_custom",
                    "text.textConfig.attentionBias=true",
                    "text.textConfig.attentionHeads=103",
                    "text.textConfig.eosTokenId[0]=132",
                    "text.textConfig.eosTokenId[1]=133",
                    "text.textConfig.fullAttentionInterval=113",
                    "text.textConfig.hcCount=114",
                    "text.textConfig.hcLowrank=115",
                    "text.textConfig.headDim=105",
                    "text.textConfig.headsPerNgram=119",
                    "text.textConfig.hiddenLayers=2",
                    "text.textConfig.hiddenSize=101",
                    "text.textConfig.indexerBudget=126",
                    "text.textConfig.indexerCompressRatio=127",
                    "text.textConfig.indexerHeadDim=125",
                    "text.textConfig.indexerKVHeads=124",
                    "text.textConfig.indexerNHeads=123",
                    "text.textConfig.kvHeads=104",
                    "text.textConfig.layerTypes[0]=qwen_sparse_attention",
                    "text.textConfig.layerTypes[1]=linear_attention",
                    "text.textConfig.linearConvKernelDim=110",
                    "text.textConfig.linearKeyHeadDim=108",
                    "text.textConfig.linearNumKeyHeads=107",
                    "text.textConfig.linearNumValueHeads=106",
                    "text.textConfig.linearValueHeadDim=109",
                    "text.textConfig.makeNgramVocabSizeDivisibleBy=121",
                    "text.textConfig.maxPositionEmbeddings=112",
                    "text.textConfig.modelType=qwen4_custom_text",
                    "text.textConfig.moeIntermediateSize=131",
                    "text.textConfig.mropeSection[0]=3",
                    "text.textConfig.mropeSection[1]=4",
                    "text.textConfig.mropeSection[2]=5",
                    "text.textConfig.mtpNumHiddenLayers=134",
                    "text.textConfig.ngramSize=118",
                    "text.textConfig.ngramVocabSizeBase=120",
                    "text.textConfig.normTopkProb=false",
                    "text.textConfig.numExperts=128",
                    "text.textConfig.numExpertsPerTok=129",
                    "text.textConfig.outputGateType=silu",
                    "text.textConfig.partialRotaryFactor=0.75",
                    "text.textConfig.pleConvKernelSize=117",
                    "text.textConfig.pleEmbedDim=116",
                    "text.textConfig.pleLayerIds[0]=1",
                    "text.textConfig.pleLayerIds[1]=2",
                    "text.textConfig.rmsNormEps=0.5",
                    "text.textConfig.ropeTheta=2.5",
                    "text.textConfig.seed=135",
                    "text.textConfig.sharedExpertIntermediateSize=130",
                    "text.textConfig.splitNgramParts=122",
                    "text.textConfig.tieWordEmbeddings=true",
                    "text.textConfig.vocabularySize=111",
                    "text.videoTokenId=141",
                    "visionConfiguration._deepstackVisualIndexes[0]=211",
                    "visionConfiguration._deepstackVisualIndexes[1]=212",
                    "visionConfiguration._hiddenAct=vision_act_b",
                    "visionConfiguration._inChannels=210",
                    "visionConfiguration.depth=201",
                    "visionConfiguration.hiddenSize=202",
                    "visionConfiguration.intermediateSize=203",
                    "visionConfiguration.modelType=vision_model_a",
                    "visionConfiguration.numHeads=205",
                    "visionConfiguration.numPositionEmbeddings=209",
                    "visionConfiguration.outHiddenSize=204",
                    "visionConfiguration.patchSize=206",
                    "visionConfiguration.spatialMergeSize=207",
                    "visionConfiguration.temporalPatchSize=208",
                ]),
            .init(
                "Qwen4ExpVideoConfiguration: Qwen4ExpVideoConfiguration",
                MLXVLM.Qwen4ExpVideoConfiguration.self,
                json:
                    #"{"fps":1.5,"image_mean":[0.25,0.375,0.625],"image_std":[0.125,0.75,0.875],"max_frames":307,"merge_size":304,"min_frames":306,"patch_size":303,"size":{"longest_edge":302,"shortest_edge":301},"temporal_patch_size":305,"video_processor_type":"Qwen3VLVideoProcessor"}"#,
                requiredKeys: [],
                fields: [
                    "fps=1.5",
                    "imageMean[0]=0.25",
                    "imageMean[1]=0.375",
                    "imageMean[2]=0.625",
                    "imageStd[0]=0.125",
                    "imageStd[1]=0.75",
                    "imageStd[2]=0.875",
                    "maxFrames=307",
                    "mergeSize=304",
                    "minFrames=306",
                    "patchSize=303",
                    "size.longestEdge=302",
                    "size.shortestEdge=301",
                    "temporalPatchSize=305",
                ]),
        ]
    }
}
