// CBv2Contracts.swift
//
// FROZEN INTEGRATION CONTRACT for the ContinuousBatchingV2 engine.
//
// Every v2 workstream (core runtime, scheduler, paged backend, prefix cache,
// sampling, model adaptation, harness, provider bridge) compiles against the
// types and protocols in this file. Do NOT edit this file in a feature
// worktree — contract changes go through the integration branch only.
//
// Design invariants this contract encodes (see docs/engine-v2/ARCHITECTURE.md):
//  - No left padding, no shared batch frontier, no batch-wide trims. Every
//    sequence owns its KV state and its absolute position counter.
//  - Decode is rectangular [B, 1] (one token per running request), so decode
//    raggedness cannot exist. Prefill runs per request as [1, chunk] under a
//    shared token budget.
//  - Sliding-window semantics are enforced by per-sequence storage eviction
//    keyed to absolute positions (never by masks over shared buffers).
//  - Attention dispatch is owned by the KV layer object (AttendingKVCache),
//    so backends (per-request SDPA v1, paged Metal kernel v2) are swappable
//    without touching models or the scheduler.

import Foundation
import MLX

// MARK: - Request & sampling surface

public struct CBv2RequestID: Hashable, Sendable, CustomStringConvertible {
    public let raw: UInt64
    public init(_ raw: UInt64) { self.raw = raw }
    public var description: String { "cbv2-\(raw)" }
}

/// Per-request sampling parameters. All fields are per-request; the sampler
/// vectorizes them into per-row tensors (never a Swift loop over rows).
public struct CBv2SamplingParams: Sendable {
    public var temperature: Float
    public var topP: Float
    public var topK: Int
    public var minP: Float
    public var repetitionPenalty: Float
    public var repetitionContextSize: Int
    public var frequencyPenalty: Float
    public var presencePenalty: Float
    /// Per-request seed. Reproducibility is best-effort under batching
    /// (documented); the RNG key is (seed, requestID, stepIndex).
    public var seed: UInt64?
    /// Token-id → additive logit bias.
    public var logitBias: [Int: Float]
    /// Number of top logprobs to report per emitted token (0 = none).
    /// Logprobs are captured from RAW logits, before any transform.
    public var topLogprobs: Int

    public init(
        temperature: Float = 1.0, topP: Float = 1.0, topK: Int = 0, minP: Float = 0,
        repetitionPenalty: Float = 1.0, repetitionContextSize: Int = 64,
        frequencyPenalty: Float = 0, presencePenalty: Float = 0,
        seed: UInt64? = nil, logitBias: [Int: Float] = [:], topLogprobs: Int = 0
    ) {
        self.temperature = temperature
        self.topP = topP
        self.topK = topK
        self.minP = minP
        self.repetitionPenalty = repetitionPenalty
        self.repetitionContextSize = repetitionContextSize
        self.frequencyPenalty = frequencyPenalty
        self.presencePenalty = presencePenalty
        self.seed = seed
        self.logitBias = logitBias
        self.topLogprobs = topLogprobs
    }
}

public struct CBv2Request: Sendable {
    public var id: CBv2RequestID
    public var promptTokens: [Int]
    public var sampling: CBv2SamplingParams
    public var maxTokens: Int
    /// Stop token ids (already resolved — string EOS resolution happens at
    /// engine construction, identically for B=1 and batched paths).
    public var stopTokens: Set<Int>
    /// Stop strings; matched against held-back detokenized text.
    public var stopStrings: [String]
    /// Higher value = more important. Used by admission and preemption.
    public var priority: Int

    public init(
        id: CBv2RequestID, promptTokens: [Int], sampling: CBv2SamplingParams = .init(),
        maxTokens: Int, stopTokens: Set<Int> = [], stopStrings: [String] = [], priority: Int = 0
    ) {
        self.id = id
        self.promptTokens = promptTokens
        self.sampling = sampling
        self.maxTokens = maxTokens
        self.stopTokens = stopTokens
        self.stopStrings = stopStrings
        self.priority = priority
    }
}

// MARK: - Layer descriptions (model structure as data)

/// Attention structure of one transformer layer, derived from model config.
/// Models declare this; the KV/attention layer validates against it.
public struct CBv2LayerKind: Sendable, Equatable {
    public enum Attention: Sendable, Equatable {
        case full
        /// Sliding-window attention with the given window (in tokens).
        case slidingWindow(Int)
    }
    public var attention: Attention
    /// Layer index whose K/V this layer reuses (Gemma-4 cross-layer KV
    /// sharing). A shared layer owns NO storage; it borrows (K, V) and the
    /// position offset from the source layer at attention time.
    public var sharesKVWithLayer: Int?
    /// Learned per-head attention sinks (GPT-OSS). Sinks are a kernel
    /// parameter (folded into the softmax denominator), never KV state.
    /// A backend that cannot honor sinks MUST be statically ineligible for
    /// models with `hasSinks == true` (it must throw at engine build).
    public var hasSinks: Bool
    public var headDim: Int
    public var kvHeads: Int
    public var queryHeads: Int

    public init(
        attention: Attention, sharesKVWithLayer: Int? = nil, hasSinks: Bool = false,
        headDim: Int, kvHeads: Int, queryHeads: Int
    ) {
        self.attention = attention
        self.sharesKVWithLayer = sharesKVWithLayer
        self.hasSinks = hasSinks
        self.headDim = headDim
        self.kvHeads = kvHeads
        self.queryHeads = queryHeads
    }
}

// MARK: - Per-sequence KV state

/// KV storage for ONE sequence at ONE layer. Self-contained: owns its
/// absolute position counter and its storage. There is no shared frontier.
public protocol CBv2SequenceKV: AnyObject {
    /// Absolute position of the next token to be written (== number of
    /// tokens processed for this sequence at this layer). Monotonic; never
    /// mutated by other sequences joining/leaving.
    var absoluteOffset: Int { get }
    /// Number of KV entries physically retained (≤ absoluteOffset for
    /// windowed caches; == absoluteOffset for full caches).
    var retainedCount: Int { get }
    /// Append K/V for `n` new tokens and return (keys, values) views suitable
    /// for attention: shapes [1, kvHeads, retainedAfterUpdate, headDim], in
    /// temporal order (oldest → newest). Windowed impls evict by absolute
    /// position and keep the RECENT end.
    func update(keys: MLXArray, values: MLXArray) -> (MLXArray, MLXArray)
    /// Zero-copy-ish snapshot for prefix-cache donation / checkpointing.
    /// Returns (keys, values, absoluteOffset) in temporal order.
    func snapshot() -> (keys: MLXArray, values: MLXArray, offset: Int)
    /// Rollback the last `n` tokens (speculative rejection). Must scrub
    /// un-confirmed tail state so it can never be attended to.
    func rollback(_ n: Int)
    /// Approximate bytes held (for accounting/telemetry).
    var byteCount: Int { get }
}

/// Factory for per-sequence KV state; implemented by the v1 contiguous
/// backend and the v2 paged backend.
public protocol CBv2KVBackend: AnyObject {
    /// Create per-layer sequence state for a new request. `layerKinds` has
    /// one entry per model layer; entries with `sharesKVWithLayer != nil`
    /// receive NO storage (return nil at that index).
    func makeSequenceState(layerKinds: [CBv2LayerKind], promptLength: Int, maxLength: Int)
        throws -> [CBv2SequenceKV?]
    /// Adopt a donated/forked prefix (prefix-cache hit). `prefix` holds
    /// per-layer snapshots for the matched token range (full-attention
    /// layers only; windowed layers are recomputed by the scheduler).
    func makeSequenceState(
        adopting prefix: [(keys: MLXArray, values: MLXArray, offset: Int)?],
        layerKinds: [CBv2LayerKind], maxLength: Int
    ) throws -> [CBv2SequenceKV?]
    /// Free all storage for a sequence (cancellation, finish, preemption).
    /// O(1) metadata for paged; releases arrays for contiguous.
    func release(_ state: [CBv2SequenceKV?])
    /// Bytes currently in use / capacity, for truthful admission.
    var bytesInUse: Int { get }
    var bytesCapacity: Int { get }
}

public enum CBv2KVError: Error {
    case capacityExhausted(needed: Int, available: Int)
    case backendIneligible(reason: String)
}

// MARK: - Attention dispatch (owned by the layer cache object)

/// The per-layer batch-facing cache object the model interacts with.
/// It conforms to the existing `KVCache` protocol so unmodified models can
/// still call `update(keys:values:)`, but v2-adapted models call
/// `updateAndAttend`, which owns BOTH the KV update and the attention
/// computation. This is what makes attention backends swappable.
public protocol CBv2AttendingLayerCache: AnyObject {
    var layerIndex: Int { get }
    var kind: CBv2LayerKind { get }
    /// Ordered per-row sequence states (row order == batch row order).
    /// Rows with different retained lengths are handled internally — the
    /// caller never pads and never builds masks.
    var rows: [CBv2SequenceKV] { get }
    /// Per-row absolute RoPE offsets, as a device array [B], for models that
    /// apply RoPE with array offsets (MLXFast.RoPE dynamic-offset overload).
    var positionOffsets: MLXArray { get }
    /// Update per-row KV with this step's K/V and compute attention.
    ///  - queries/keys/values: [B, heads, L, headDim]; L == 1 for decode,
    ///    B == 1 for prefill chunks.
    ///  - sinks: per-head learned sink logits, or nil.
    ///  - Returns attention output [B, queryHeads, L, headDim].
    /// Implementations MUST be numerically pinned: one attention path per
    /// (model, phase), never switching mask representation across steps.
    func updateAndAttend(
        queries: MLXArray, keys: MLXArray, values: MLXArray,
        scale: Float, sinks: MLXArray?
    ) -> MLXArray
    /// Borrow the source layer's K/V for Gemma-style KV-shared layers.
    /// Only valid when `kind.sharesKVWithLayer != nil`.
    func attendBorrowing(
        source: CBv2AttendingLayerCache,
        queries: MLXArray, scale: Float, sinks: MLXArray?
    ) -> MLXArray
}

// MARK: - Scheduler plan (vLLM-V1 style: no phases)

public enum CBv2RequestStatus: Sendable, Equatable {
    case waiting
    case running        // numComputedTokens < numTokens ⇒ still prefilling
    case preempted
    case finished(CBv2FinishReason)
}

public enum CBv2FinishReason: Sendable, Equatable {
    case stop           // stop token or stop string
    case length         // maxTokens or context limit
    case cancelled
    case error(String)
}

/// One step's work assignment: token counts per request under a single
/// budget. Decode requests get 1 (or 1+k with speculation later); prefilling
/// requests get a chunk. There is no prefill/decode phase distinction.
public struct CBv2StepPlan: Sendable {
    public var assignments: [(id: CBv2RequestID, numTokens: Int)]
    public var preemptions: [CBv2RequestID]
    public init(
        assignments: [(id: CBv2RequestID, numTokens: Int)] = [],
        preemptions: [CBv2RequestID] = []
    ) {
        self.assignments = assignments
        self.preemptions = preemptions
    }
}

public struct CBv2SchedulerConfig: Sendable {
    /// Hard cap on concurrently RUNNING requests (product target: 4, max 8).
    public var maxConcurrentRequests: Int
    /// Token budget per step across decode + prefill chunks.
    public var maxBatchedTokensPerStep: Int
    /// Preferred prefill chunk size (adaptive sizer may override).
    public var prefillChunkSize: Int
    /// Max queue depth before rejecting with capacity error.
    public var maxWaiting: Int
    public init(
        maxConcurrentRequests: Int = 4, maxBatchedTokensPerStep: Int = 2048,
        prefillChunkSize: Int = 512, maxWaiting: Int = 64
    ) {
        self.maxConcurrentRequests = maxConcurrentRequests
        self.maxBatchedTokensPerStep = maxBatchedTokensPerStep
        self.prefillChunkSize = prefillChunkSize
        self.maxWaiting = maxWaiting
    }
}

// MARK: - Engine events (provider/consumer surface)

public struct CBv2TokenLogprob: Sendable {
    public var token: Int
    public var logprob: Float
    public var topLogprobs: [(token: Int, logprob: Float)]
    public init(token: Int, logprob: Float, topLogprobs: [(token: Int, logprob: Float)] = []) {
        self.token = token
        self.logprob = logprob
        self.topLogprobs = topLogprobs
    }
}

public enum CBv2Event: Sendable {
    /// New generated text, already detokenized incrementally with UTF-8 and
    /// stop-string holdback applied (never emits text past a stop match).
    case delta(text: String, tokens: [Int], logprobs: [CBv2TokenLogprob]?)
    case finished(reason: CBv2FinishReason, usage: CBv2Usage)
}

public struct CBv2Usage: Sendable {
    public var promptTokens: Int
    public var completionTokens: Int
    public var prefixCacheHitTokens: Int
    public init(promptTokens: Int, completionTokens: Int, prefixCacheHitTokens: Int = 0) {
        self.promptTokens = promptTokens
        self.completionTokens = completionTokens
        self.prefixCacheHitTokens = prefixCacheHitTokens
    }
}

/// Capacity snapshot for provider heartbeats (same field semantics as today,
/// but numbers become truthful: actual bytes/tokens in use, not worst case).
public struct CBv2CapacitySnapshot: Sendable {
    public var activeRequests: Int
    public var waitingRequests: Int
    public var kvBytesInUse: Int
    public var kvBytesCapacity: Int
    public var activeTokens: Int
    public init(
        activeRequests: Int, waitingRequests: Int, kvBytesInUse: Int, kvBytesCapacity: Int,
        activeTokens: Int
    ) {
        self.activeRequests = activeRequests
        self.waitingRequests = waitingRequests
        self.kvBytesInUse = kvBytesInUse
        self.kvBytesCapacity = kvBytesCapacity
        self.activeTokens = activeTokens
    }
}

// MARK: - Prefix cache

/// Content-addressed prefix cache over per-sequence KV snapshots.
/// Keys are SHA-256 chain hashes at fixed block granularity (256 tokens),
/// compatible with the existing on-disk checkpoint tier.
public protocol CBv2PrefixCache: AnyObject {
    /// Longest cached prefix for `tokens`, in whole blocks.
    /// Returns nil or (matchedTokenCount, per-layer snapshots for
    /// full-attention layers; windowed layers are always nil — the engine
    /// recomputes the trailing `window` tokens for those layers).
    func lookup(tokens: [Int], layerKinds: [CBv2LayerKind])
        -> (matched: Int, prefix: [(keys: MLXArray, values: MLXArray, offset: Int)?])?
    /// Donate a finished request's state. Zero-copy move; the cache owns the
    /// arrays afterwards. Must be called OFF the engine step thread.
    func donate(
        tokens: [Int], state: [CBv2SequenceKV?], layerKinds: [CBv2LayerKind])
    /// Evict to fit `byteBudget`. LRU.
    func evict(toFit byteBudget: Int)
    var bytesInUse: Int { get }
}

// MARK: - Engine public API (what the provider binds to)

public protocol CBv2Engine: AnyObject {
    /// Submit a request; events stream until `.finished`.
    /// Throws CBv2KVError.capacityExhausted when admission fails (the
    /// provider maps this to 429/503 exactly as today).
    func submit(_ request: CBv2Request) throws -> AsyncStream<CBv2Event>
    /// Cancel promptly: in-flight step completes, row is dropped O(1).
    func cancel(_ id: CBv2RequestID)
    func capacity() -> CBv2CapacitySnapshot
    /// Graceful drain: finish running requests, reject new submissions.
    func shutdown() async
}
